<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Barker">
<meta name="dcterms.date" content="2026-04-20">

<title>Chapter 10 - Transaction Exposure – International Finance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a2e98a8173336b0a3fc6fb521ab0b9ac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">International Finance</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Lecture Notes</li><li class="breadcrumb-item"><a href="../lectures/Chapter01_Lecture.html">Lectures</a></li><li class="breadcrumb-item"><a href="../lectures/Chapter10_Lecture_Math_Compliant.html">Chapter 10 - Transaction Exposure</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Lecture Notes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Lectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter01_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1 - Multinational Financial Management: Opportunities and Challenges</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter02_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2 - International Monetary System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter02.1_2026_Currency_example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2.1 - 2026 Example</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter03_LectureA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3 - The Balance of Payments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter04_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4 - Financial Goals, Corporate Governance, and the Market for Corporate Control</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter05_Lecture_FIXED.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5 - The Foreign Exchange Market</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter06_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 6 - International Parity Conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter09_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 9 - Foreign Exchange Rate Determination and Intervention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter10_Lecture_Math_Compliant.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 10 - Transaction Exposure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter12_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 12 - Operating Exposure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter16_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 16 - International Trade Finance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Chapter17_Lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 17 - Foreign Direct Investment and Political Risk</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">IF Simulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview - START HERE</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/fx_dashboard_round6_final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Global Dashboard</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/roles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Roles and Responsibilities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/countries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Countries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decisions and Rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/deliverables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deliverables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/trade_fx_options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trade and Alliance Board</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/Weekly_Brief_sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weekly Brief – EXAMPLE ONLY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Market Reactions &amp; FAQs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../simulation/grading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluation and Rubric</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">10</span> Introduction</a>
  <ul>
  <li><a href="#chapter-roadmap" id="toc-chapter-roadmap" class="nav-link" data-scroll-target="#chapter-roadmap">Chapter Roadmap</a></li>
  <li><a href="#types-of-foreign-exchange-exposure" id="toc-types-of-foreign-exchange-exposure" class="nav-link" data-scroll-target="#types-of-foreign-exchange-exposure"><span class="header-section-number">10.1</span> Types of Foreign Exchange Exposure</a>
  <ul class="collapse">
  <li><a href="#transaction-exposure" id="toc-transaction-exposure" class="nav-link" data-scroll-target="#transaction-exposure"><span class="header-section-number">10.1.1</span> Transaction Exposure</a></li>
  <li><a href="#translation-exposure" id="toc-translation-exposure" class="nav-link" data-scroll-target="#translation-exposure"><span class="header-section-number">10.1.2</span> Translation Exposure</a></li>
  <li><a href="#operating-exposure" id="toc-operating-exposure" class="nav-link" data-scroll-target="#operating-exposure"><span class="header-section-number">10.1.3</span> Operating Exposure</a></li>
  </ul></li>
  <li><a href="#why-hedge" id="toc-why-hedge" class="nav-link" data-scroll-target="#why-hedge"><span class="header-section-number">10.2</span> Why Hedge?</a>
  <ul class="collapse">
  <li><a href="#hedging-defined" id="toc-hedging-defined" class="nav-link" data-scroll-target="#hedging-defined"><span class="header-section-number">10.2.1</span> Hedging Defined</a></li>
  <li><a href="#the-pros-and-cons-of-hedging" id="toc-the-pros-and-cons-of-hedging" class="nav-link" data-scroll-target="#the-pros-and-cons-of-hedging"><span class="header-section-number">10.2.2</span> The Pros and Cons of Hedging</a></li>
  <li><a href="#pros" id="toc-pros" class="nav-link" data-scroll-target="#pros"><span class="header-section-number">10.2.3</span> Pros</a></li>
  <li><a href="#cons" id="toc-cons" class="nav-link" data-scroll-target="#cons"><span class="header-section-number">10.2.4</span> Cons</a></li>
  </ul></li>
  <li><a href="#transaction-exposure-1" id="toc-transaction-exposure-1" class="nav-link" data-scroll-target="#transaction-exposure-1"><span class="header-section-number">10.3</span> Transaction Exposure</a>
  <ul class="collapse">
  <li><a href="#purchasing-and-selling" id="toc-purchasing-and-selling" class="nav-link" data-scroll-target="#purchasing-and-selling"><span class="header-section-number">10.3.1</span> Purchasing and Selling</a>
  <ul class="collapse">
  <li><a href="#the-life-span-of-transaction-exposure" id="toc-the-life-span-of-transaction-exposure" class="nav-link" data-scroll-target="#the-life-span-of-transaction-exposure"><span class="header-section-number">10.3.1.1</span> <strong>The life span of transaction exposure</strong></a></li>
  </ul></li>
  <li><a href="#borrowing-and-lending" id="toc-borrowing-and-lending" class="nav-link" data-scroll-target="#borrowing-and-lending"><span class="header-section-number">10.3.2</span> Borrowing and Lending</a></li>
  <li><a href="#other-causes-of-transaction-exposure" id="toc-other-causes-of-transaction-exposure" class="nav-link" data-scroll-target="#other-causes-of-transaction-exposure"><span class="header-section-number">10.3.3</span> Other Causes of Transaction Exposure</a></li>
  </ul></li>
  <li><a href="#transaction-exposure-management" id="toc-transaction-exposure-management" class="nav-link" data-scroll-target="#transaction-exposure-management"><span class="header-section-number">10.4</span> Transaction Exposure Management</a>
  <ul class="collapse">
  <li><a href="#ganados-transaction-exposure" id="toc-ganados-transaction-exposure" class="nav-link" data-scroll-target="#ganados-transaction-exposure"><span class="header-section-number">10.4.1</span> Ganado’s Transaction Exposure</a></li>
  <li><a href="#unhedged-position" id="toc-unhedged-position" class="nav-link" data-scroll-target="#unhedged-position"><span class="header-section-number">10.4.2</span> Unhedged Position</a></li>
  <li><a href="#forward-hedge" id="toc-forward-hedge" class="nav-link" data-scroll-target="#forward-hedge"><span class="header-section-number">10.4.3</span> Forward Hedge</a></li>
  <li><a href="#money-market-hedge-balance-sheet-hedge" id="toc-money-market-hedge-balance-sheet-hedge" class="nav-link" data-scroll-target="#money-market-hedge-balance-sheet-hedge"><span class="header-section-number">10.4.4</span> Money Market Hedge (Balance Sheet Hedge)</a></li>
  <li><a href="#forward-and-money-market-hedges-compared" id="toc-forward-and-money-market-hedges-compared" class="nav-link" data-scroll-target="#forward-and-money-market-hedges-compared"><span class="header-section-number">10.4.5</span> Forward and Money Market Hedges Compared</a>
  <ul class="collapse">
  <li><a href="#break-even-reinvestment-rate" id="toc-break-even-reinvestment-rate" class="nav-link" data-scroll-target="#break-even-reinvestment-rate"><span class="header-section-number">10.4.5.1</span> Break-even reinvestment rate</a></li>
  </ul></li>
  <li><a href="#options-market-hedge" id="toc-options-market-hedge" class="nav-link" data-scroll-target="#options-market-hedge"><span class="header-section-number">10.4.6</span> Options Market Hedge</a>
  <ul class="collapse">
  <li><a href="#if-the-pound-is-above-the-strike-at-maturity" id="toc-if-the-pound-is-above-the-strike-at-maturity" class="nav-link" data-scroll-target="#if-the-pound-is-above-the-strike-at-maturity"><span class="header-section-number">10.4.6.1</span> If the pound is above the strike at maturity</a></li>
  <li><a href="#if-the-pound-falls-below-the-strike" id="toc-if-the-pound-falls-below-the-strike" class="nav-link" data-scroll-target="#if-the-pound-falls-below-the-strike"><span class="header-section-number">10.4.6.2</span> If the pound falls below the strike</a></li>
  </ul></li>
  <li><a href="#hedging-alternatives-compared" id="toc-hedging-alternatives-compared" class="nav-link" data-scroll-target="#hedging-alternatives-compared"><span class="header-section-number">10.4.7</span> Hedging Alternatives Compared</a></li>
  <li><a href="#hedging-an-account-payable" id="toc-hedging-an-account-payable" class="nav-link" data-scroll-target="#hedging-an-account-payable"><span class="header-section-number">10.4.8</span> Hedging an Account Payable</a>
  <ul class="collapse">
  <li><a href="#remain-unhedged" id="toc-remain-unhedged" class="nav-link" data-scroll-target="#remain-unhedged"><span class="header-section-number">10.4.8.1</span> Remain Unhedged</a></li>
  <li><a href="#forward-market-hedge" id="toc-forward-market-hedge" class="nav-link" data-scroll-target="#forward-market-hedge"><span class="header-section-number">10.4.8.2</span> Forward Market Hedge</a></li>
  <li><a href="#money-market-hedge" id="toc-money-market-hedge" class="nav-link" data-scroll-target="#money-market-hedge"><span class="header-section-number">10.4.8.3</span> Money Market Hedge</a></li>
  <li><a href="#option-hedge" id="toc-option-hedge" class="nav-link" data-scroll-target="#option-hedge"><span class="header-section-number">10.4.8.4</span> Option Hedge</a></li>
  <li><a href="#strategy-choice" id="toc-strategy-choice" class="nav-link" data-scroll-target="#strategy-choice"><span class="header-section-number">10.4.8.5</span> Strategy Choice</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#transaction-exposure-management-in-practice" id="toc-transaction-exposure-management-in-practice" class="nav-link" data-scroll-target="#transaction-exposure-management-in-practice"><span class="header-section-number">10.5</span> Transaction Exposure Management in Practice</a>
  <ul class="collapse">
  <li><a href="#which-goals" id="toc-which-goals" class="nav-link" data-scroll-target="#which-goals"><span class="header-section-number">10.5.1</span> Which Goals</a></li>
  <li><a href="#which-transaction-exposures" id="toc-which-transaction-exposures" class="nav-link" data-scroll-target="#which-transaction-exposures"><span class="header-section-number">10.5.2</span> Which Transaction Exposures</a></li>
  <li><a href="#what-levels-of-exposure-cover" id="toc-what-levels-of-exposure-cover" class="nav-link" data-scroll-target="#what-levels-of-exposure-cover"><span class="header-section-number">10.5.3</span> What Levels of Exposure Cover</a></li>
  <li><a href="#which-hedging-instruments-and-structures" id="toc-which-hedging-instruments-and-structures" class="nav-link" data-scroll-target="#which-hedging-instruments-and-structures"><span class="header-section-number">10.5.4</span> Which Hedging Instruments and Structures</a>
  <ul class="collapse">
  <li><a href="#hedging-practices" id="toc-hedging-practices" class="nav-link" data-scroll-target="#hedging-practices"><span class="header-section-number">10.5.4.1</span> Hedging practices</a></li>
  <li><a href="#hedging-instruments" id="toc-hedging-instruments" class="nav-link" data-scroll-target="#hedging-instruments"><span class="header-section-number">10.5.4.2</span> Hedging instruments</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Chapter10_Lecture_Math_Compliant.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="Chapter10_Lecture_Math_Compliant.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Lecture Notes</li><li class="breadcrumb-item"><a href="../lectures/Chapter01_Lecture.html">Lectures</a></li><li class="breadcrumb-item"><a href="../lectures/Chapter10_Lecture_Math_Compliant.html">Chapter 10 - Transaction Exposure</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Chapter 10 - Transaction Exposure</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Barker </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Introduction</h1>
<p>Random Quote (One of the most comforting things I have heard): <strong>“When God put a calling on my life, He already factored in my stupidity.”</strong></p>
<p>Bible Quote: <strong>“The plans of the diligent lead surely to abundance,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;but everyone who is hasty comes only to poverty.”</strong> <strong>-Proverbs 21:5</strong></p>
<p>Textbook Quote: <strong>“There are two times in a man’s life when he should not speculate: when he can’t afford it and when he can.”</strong></p>
<ul>
<li>“Following the Equator, Pudd’nhead Wilson’s New Calendar,” Mark Twain</li>
</ul>
<p><strong>From the first paragraph of the chapter:</strong> “Foreign exchange exposure is a measure of the potential for a firm’s profitability, net cash flow, and market value to change because of a change in exchange rates. An important task of the financial manager is to measure foreign exchange exposure and to manage it so as to maximize the profitability, net cash flow, and market value of the firm.”</p>
<p><strong>Central Problem of the chapter:</strong> once exchange rates move, how does that movement affect the firm’s actual contracts, cash flows, reported income, and treasury decisions?</p>
<p>This chapter focuses on <strong>transaction exposure</strong>, the most immediate and visible form of foreign exchange exposure. It is immediate because it affects specific receivables, payables, loans, and contractual settlements. It is visible because the resulting gains and losses often appear directly in reported earnings. For that reason, transaction exposure is often the form of exposure that receives the most attention from treasury managers and chief financial officers.</p>
<p>The central logic of the chapter is straightforward:</p>
<ul>
<li>Firms face foreign exchange exposure because business contracts are often denominated in foreign currencies.</li>
<li>Exchange-rate changes alter the domestic-currency value of those contractual cash flows.</li>
<li>Treasury can either leave the exposure unhedged or manage it with forwards, money market positions, or options.</li>
<li>The appropriate choice depends on the firm’s risk tolerance, expected exchange-rate movements, costs of hedging, and managerial objectives.</li>
</ul>
<section id="chapter-roadmap" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="chapter-roadmap">Chapter Roadmap</h2>
<p>Major sections:</p>
<ol type="1">
<li><strong>Types of Foreign Exchange Exposure</strong> - Distinguishes transaction, translation, and operating exposure.</li>
<li><strong>Why Hedge?</strong> - Explains why firms do or do not hedge currency risk.</li>
<li><strong>Transaction Exposure</strong> - Defines the exposure and shows how it arises from trade, borrowing, and contracts.</li>
<li><strong>Transaction Exposure Management</strong> - Demonstrates the mechanics of unhedged, forward, money market, and options hedges.</li>
<li><strong>Transaction Exposure Management in Practice</strong> - Examines how firms actually hedge, what they hedge, and which instruments they use most often.</li>
</ol>
<hr>
</section>
<section id="types-of-foreign-exchange-exposure" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="types-of-foreign-exchange-exposure"><span class="header-section-number">10.1</span> Types of Foreign Exchange Exposure</h2>
<p>A multinational firm does not face only one kind of currency risk. It faces <strong>three distinct types of foreign exchange exposure</strong>, and these exposures differ in both economic meaning and financial statement impact.</p>
<p>From our textbook:</p>
<section id="transaction-exposure" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="transaction-exposure"><span class="header-section-number">10.1.1</span> Transaction Exposure</h3>
<ul>
<li>measures changes in the value of contractual obligations incurred between the time in which they are created and booked, and when they are settled due to a change in exchange rates.</li>
</ul>
<p>Typical examples include:</p>
<ul>
<li>a foreign-currency <strong>account receivable</strong> from an export sale,</li>
<li>a foreign-currency <strong>account payable</strong> for an import purchase,</li>
<li>a foreign-currency <strong>loan payable</strong>, or</li>
<li>a <strong>forward contract</strong> itself, once it is signed.</li>
</ul>
</section>
<section id="translation-exposure" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="translation-exposure"><span class="header-section-number">10.1.2</span> Translation Exposure</h3>
<ul>
<li>the potential for accounting-derived changes in owner’s equity or consolidated income to occur because of the need to “translate” foreign currency to prepare worldwide consolidated financial statements.</li>
</ul>
<p>Such as:</p>
<ul>
<li><strong>Transaction losses</strong> are realized and typically affect taxable income in the year realized.</li>
<li><strong>Translation losses</strong> are accounting losses and are generally not cash losses; therefore, they are usually not tax deductible as realized operating losses.</li>
</ul>
</section>
<section id="operating-exposure" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="operating-exposure"><span class="header-section-number">10.1.3</span> Operating Exposure</h3>
<ul>
<li>also commonly called <strong>economic</strong> or <strong>competitive</strong> exposure, measures the changes in the present value of the firm resulting from any change in future operating cash flows of the firm caused by an unexpected change in exchange rates. The change in value depends on the effect of the exchange rate change on future sales volume, prices, and costs.</li>
</ul>
<p>Examples include:</p>
<ul>
<li>a stronger home currency making exports less competitive,</li>
<li>a weaker foreign rival’s currency pressuring prices in third-country markets,</li>
<li>imported inputs becoming cheaper after home-currency appreciation, or</li>
<li>future foreign sales becoming more valuable in home-currency terms.</li>
</ul>
<p>A useful summary is provided below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Exposure Type</th>
<th>Core Idea</th>
<th>Time Horizon</th>
<th>Financial Statement Effects</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Transaction exposure</strong></td>
<td>Change in value of existing foreign-currency contractual cash flows</td>
<td>Short- to medium-term</td>
<td>Cash Flows and Profitability</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Translation exposure</strong></td>
<td>Change in reported consolidated statements when foreign subsidiaries are translated into parent currency</td>
<td>Accounting period by accounting period</td>
<td>Income and Equity, but not Cash Flows</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Operating exposure</strong></td>
<td>Change in the present value of future operating cash flows caused by unexpected exchange-rate changes</td>
<td>Medium- to long-term</td>
<td>Possibly everything, but not in the current period</td>
<td></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="why-hedge" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="why-hedge"><span class="header-section-number">10.2</span> Why Hedge?</h2>
<p>“Multinational firms consist of a multitude of cash flows that are sensitive to changes in exchange rates, interest rates, and commodity prices. These outstanding obligations and contracts are altered by changes in exchange rates.</p>
<section id="hedging-defined" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="hedging-defined"><span class="header-section-number">10.2.1</span> Hedging Defined</h3>
<p>A <strong>hedge</strong> can help to manage this risk. Hedging requires a firm to take a position—an asset, contract, or derivative—the value of which will rise or fall in a manner that counter the fall or rise in value of an existing position - the exposure. Hedging protects against the possible loss, but also eliminates any gain from an increase in value as well. So what is gained from hedging?</p>
<p>According to finance theory, the value of the firm is the present value of all expected future cash flows.</p>
<p>Hedging does not normally increase the expected cash flow itself. Instead, it reduces the <strong>variance</strong> around that expectation.</p>
<p>A useful conceptual picture is this:</p>
<ul>
<li><strong>Unhedged firm:</strong> wider distribution of possible cash flows.</li>
<li><strong>Hedged firm:</strong> narrower distribution around the mean.</li>
</ul>
<p>That narrower distribution means <strong>less risk</strong>. It does <strong>not automatically mean higher expected value</strong>.</p>
<p>Graphically, the distribution of possible cash flows becomes narrower (think of a normal distribution, and then a second distribution more tightly centered around the mean).</p>
<p>Hedging reduces the variability of expected cash flows about the mean of the distribution. This reduction in distribution variance is a reduction of risk.</p>
<p><strong>Important point</strong> Hedging does not increase or decrease profitability by itself, it is only reducing the risk. If the normal distribution moved to the right, then the hedge would be increasing the profitability of the firm (or vice versa).</p>
</section>
<section id="the-pros-and-cons-of-hedging" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="the-pros-and-cons-of-hedging"><span class="header-section-number">10.2.2</span> The Pros and Cons of Hedging</h3>
<p>There is substantial debate in finance over whether firms should hedge currency risk. This is not a trivial disagreement. It reflects different views about market efficiency, managerial incentives, financial distress, and shareholder diversification.</p>
</section>
<section id="pros" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="pros"><span class="header-section-number">10.2.3</span> Pros</h3>
<p><strong>1. Hedging improves planning.</strong><br>
If future cash flows are more predictable, management can budget, invest, and finance the firm more confidently. A reduction in uncertainty may make otherwise desirable projects feasible.</p>
<p><strong>2. Hedging reduces the probability of financial distress.</strong><br>
If exchange-rate movements can push cash flows below a critical minimum needed for debt service or operations, hedging lowers the chance that the firm crosses that dangerous threshold.</p>
<p><strong>3. Management may understand the firm’s actual currency exposures better than outside shareholders.</strong><br>
Managers know invoice currency, supplier practices, pricing terms, and internal exposures in a way investors generally do not.</p>
<p><strong>4. Management may identify disequilibrium conditions.</strong><br>
If markets are not always in perfect equilibrium, management may selectively hedge when conditions are especially favorable or dangerous.</p>
</section>
<section id="cons" class="level3" data-number="10.2.4">
<h3 data-number="10.2.4" class="anchored" data-anchor-id="cons"><span class="header-section-number">10.2.4</span> Cons</h3>
<p><strong>1. Shareholders can diversify on their own.</strong><br>
Investors may prefer to manage currency risk through portfolio diversification rather than have the corporation do it for them.</p>
<p><strong>2. Hedging does not increase expected cash flows.</strong><br>
A hedge typically reduces variance, not expected value. Since hedging often has explicit or implicit cost, it may even reduce expected net cash flow.</p>
<p><strong>3. Agency problems may distort hedging decisions.</strong><br>
Managers are often more risk-averse than shareholders. They may hedge to protect their own careers or accounting outcomes rather than to maximize shareholder value.</p>
<p><strong>4. Managers cannot systematically outguess the market.</strong><br>
If parity conditions and market efficiency broadly hold, the expected net present value of hedging should be near zero before costs.</p>
<p><strong>5. Hedging may be motivated by optics rather than value.</strong><br>
Foreign exchange losses show up visibly in financial statements. Hedging costs may be buried elsewhere. This can bias managerial decision-making.</p>
<p><strong>6. Efficient market theorists believe that investors see through the “accounting veil.”</strong> Therefore, they understand what management is doing and only see hedging as an added cost of doing business.</p>
<p>A hedge adds value only if the benefits of lower volatility, lower distress cost, better planning, or better market access are large enough to exceed the cost of the hedge. Hedging does not add return.</p>
</section>
</section>
<section id="transaction-exposure-1" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="transaction-exposure-1"><span class="header-section-number">10.3</span> Transaction Exposure</h2>
<p>Transaction exposure measures gains or losses that arise from the settlement of existing financial obligations whose terms are stated in a foreign currency. In plain language, the contract already exists, but the exchange rate at settlement is still unknown.</p>
<p>This exposure arises most often from three classes of activity:</p>
<ol type="1">
<li><strong>Purchasing or selling goods or services</strong> in foreign currency,</li>
<li><strong>Borrowing or lending funds</strong> in foreign currency, and</li>
<li><strong>Entering other foreign-currency-denominated obligations</strong>, including some derivative contracts.</li>
</ol>
<section id="purchasing-and-selling" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="purchasing-and-selling"><span class="header-section-number">10.3.1</span> Purchasing and Selling</h3>
<p>The most common source of transaction exposure is trade.</p>
<p>Suppose a U.S. exporter sells merchandise to a Belgian buyer for <strong>EUR 1,800,000</strong>, payable in 60 days. On the date of sale, the spot rate is:</p>
<p><span class="math display">\[
\text{USD }1.1200 = \text{EUR }1.00
\]</span></p>
<p>So the receivable is booked at:</p>
<p><span class="math display">\[
\text{EUR }1,800,000 \times \text{USD }1.1200 = \text{USD }2,016,000
\]</span></p>
<p>That booked amount is not the final dollar amount actually received. If, by the settlement date, the euro weakens to:</p>
<p><span class="math display">\[
\text{USD }1.1000 = \text{EUR }1.00
\]</span></p>
<p>then the actual dollars received become:</p>
<p><span class="math display">\[
\text{EUR }1,800,000 \times \text{USD }1.1000 = \text{USD }1,980,000
\]</span></p>
<p>So the foreign exchange gain or loss is:</p>
<p><span class="math display">\[
\text{FX gain (loss)} = \text{USD }1,980,000 - \text{USD }2,016,000 = -\text{USD }36,000
\]</span></p>
<p>If instead the euro strengthens to:</p>
<p><span class="math display">\[
\text{USD }1.3000 = \text{EUR }1.00
\]</span></p>
<p>then settlement becomes:</p>
<p><span class="math display">\[
\text{EUR }1,800,000 \times \text{USD }1.3000 = \text{USD }2,340,000
\]</span></p>
<p>and the exporter realizes a gain of:</p>
<p><span class="math display">\[
\text{USD }2,340,000 - \text{USD }2,016,000 = \text{USD }324,000
\]</span></p>
<p>So a foreign-currency receivable contains both downside risk and upside potential.</p>
<section id="the-life-span-of-transaction-exposure" class="level4" data-number="10.3.1.1">
<h4 data-number="10.3.1.1" class="anchored" data-anchor-id="the-life-span-of-transaction-exposure"><span class="header-section-number">10.3.1.1</span> <strong>The life span of transaction exposure</strong></h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/images/Ch10/Transaction_Exposure.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>The Life Span of a Transaction Exposure</figcaption>
</figure>
</div>
<p>Some firms do not formally treat quotation exposure or backlog exposure as hedgeable transaction exposure because the contract may still change or be cancelled. Other firms, especially those with predictable business patterns, do hedge some of these earlier stages.</p>
</section>
</section>
<section id="borrowing-and-lending" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="borrowing-and-lending"><span class="header-section-number">10.3.2</span> Borrowing and Lending</h3>
<p>A second source of transaction exposure arises when firms borrow or lend in foreign currency.</p>
<p>The chapter uses the example of <strong>Gemex</strong>, PepsiCo’s large Mexican bottler in the mid-1990s. Gemex had U.S. dollar debt of <strong>USD 264 million</strong>. When the Mexican peso was around:</p>
<p><span class="math display">\[
\text{MXN }3.45 = \text{USD }1.00
\]</span></p>
<p>the peso value of that debt was:</p>
<p><span class="math display">\[
\text{USD }264,000,000 \times \text{MXN }3.45 = \text{MXN }910,800,000
\]</span></p>
<p>After the peso weakened sharply to about:</p>
<p><span class="math display">\[
\text{MXN }5.50 = \text{USD }1.00
\]</span></p>
<p>the peso value of the same dollar debt became:</p>
<p><span class="math display">\[
\text{USD }264,000,000 \times \text{MXN }5.50 = \text{MXN }1,452,000,000
\]</span></p>
<p>So the peso burden of the debt increased by:</p>
<p><span class="math display">\[
\text{MXN }1,452,000,000 - \text{MXN }910,800,000 = \text{MXN }541,200,000
\]</span></p>
<p>This illustrates a critical point: even when the debt amount in foreign currency is fixed, the <strong>home-currency burden</strong> can change dramatically.</p>
<p>For a borrower with domestic-currency cash flows, this can create severe financial stress.</p>
</section>
<section id="other-causes-of-transaction-exposure" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="other-causes-of-transaction-exposure"><span class="header-section-number">10.3.3</span> Other Causes of Transaction Exposure</h3>
<p>Transaction exposure also arises from <strong>forward exchange contracts</strong> and other contractual positions entered into to hedge or finance the firm.</p>
<p>For example, suppose a U.S. importer owes <strong>JPY 100 million</strong> in 90 days for an import purchase. It may hedge that payable by buying <strong>JPY 100 million forward</strong> today for delivery in 90 days. That forward contract itself is now a contractual obligation. Even though it was created as a hedge, it is also a transaction exposure because the firm is committed to settle the contract.</p>
<p>This is conceptually important: a hedge is still a contract. If the underlying commercial exposure disappears <strong>(a cancelled order)</strong>, the hedge may remain and become its own problem unless it is offset, reversed, or restructured.</p>
</section>
</section>
<section id="transaction-exposure-management" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="transaction-exposure-management"><span class="header-section-number">10.4</span> Transaction Exposure Management</h2>
<p>Once a transaction exposure exists, management must decide how to respond. The broad menu includes:</p>
<ul>
<li>leaving the exposure <strong>unhedged</strong>,</li>
<li>using a <strong>forward hedge</strong>,</li>
<li>using a <strong>money market hedge</strong> (also called a <strong>balance sheet hedge</strong>),</li>
<li>using an <strong>options market hedge</strong>, or</li>
<li>using operating policies such as natural hedges, risk-sharing, or timing adjustments.</li>
</ul>
<p>This chapter emphasizes the <strong>contractual or financial hedges</strong>. These are the techniques most frequently used for clearly identifiable short-term exposures.</p>
<section id="ganados-transaction-exposure" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="ganados-transaction-exposure"><span class="header-section-number">10.4.1</span> Ganado’s Transaction Exposure</h3>
<p>The textbook’s central example is <strong>Ganado</strong>, a U.S. firm that sells a turbine generator to a British company, Regency, for:</p>
<p><span class="math display">\[
\text{GBP }1,000,000
\]</span></p>
<p>with payment due in 90 days.</p>
<p>The key market data are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Item</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Spot rate</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1.7640 = \text{GBP }1.00 \]</span></td>
</tr>
<tr class="even">
<td>90-day forward rate</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1.7540 = \text{GBP }1.00 \]</span></td>
</tr>
<tr class="odd">
<td>Expected future spot</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1.7600 = \text{GBP }1.00 \]</span></td>
</tr>
<tr class="even">
<td>U.S. 90-day borrowing rate</td>
<td style="text-align: right;">2.00%</td>
</tr>
<tr class="odd">
<td>U.S. 90-day investment rate</td>
<td style="text-align: right;">1.50%</td>
</tr>
<tr class="even">
<td>U.K. 90-day investment rate</td>
<td style="text-align: right;">2.00%</td>
</tr>
<tr class="odd">
<td>U.K. 90-day borrowing rate</td>
<td style="text-align: right;">2.50%</td>
</tr>
<tr class="even">
<td>Ganado WACC for 90 days</td>
<td style="text-align: right;">3.00%</td>
</tr>
<tr class="odd">
<td>90-day put option strike</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1.75 = \text{GBP }1.00 \]</span></td>
</tr>
<tr class="even">
<td>Put premium</td>
<td style="text-align: right;">1.5%</td>
</tr>
</tbody>
</table>
<p>The sale was booked at:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.7640 = \text{USD }1,764,000
\]</span></p>
<p>Ganado’s <strong>budget rate</strong>—the lowest acceptable dollar value consistent with minimum profitability—is:</p>
<p><span class="math display">\[
\text{USD }1.70 = \text{GBP }1.00
\]</span></p>
<p>That budget rate matters because it means management is not merely choosing the mathematically best hedge; it is choosing a hedge consistent with the firm’s minimum acceptable margin (below this rate, Ganado will not make a profit).</p>
</section>
<section id="unhedged-position" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="unhedged-position"><span class="header-section-number">10.4.2</span> Unhedged Position</h3>
<p>The unhedged strategy is the simplest:</p>
<ul>
<li>do nothing today,</li>
<li>receive pounds in 90 days,</li>
<li>convert them at the then-current spot rate.</li>
</ul>
<p>If the expected spot rate occurs,</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.7600 = \text{USD }1,760,000
\]</span></p>
<p>But if the pound falls to, say,</p>
<p><span class="math display">\[
\text{USD }1.65 = \text{GBP }1.00
\]</span></p>
<p>Ganado would receive only:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.65 = \text{USD }1,650,000
\]</span></p>
<p>That would fall <strong>below</strong> the budget rate threshold of USD 1.70 per GBP and could wipe out the deal’s expected profit and create a probable loss of $50,000.</p>
<p>The appeal of remaining unhedged is upside participation. Had the US currency weakened, there would have been a profit for Ganado that would not have been limited by a hedge. The weakness is obvious: full downside exposure remains due to the lack of hedging.</p>
</section>
<section id="forward-hedge" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="forward-hedge"><span class="header-section-number">10.4.3</span> Forward Hedge</h3>
<p>A <strong>forward hedge</strong> locks in a future exchange rate today.</p>
<p>Since Ganado will receive pounds in the future, it should <strong>sell pounds forward</strong> today at the 90-day forward rate:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \text{ forward at } \text{USD }1.7540 = \text{GBP }1.00
\]</span></p>
<p>In 90 days Ganado receives the pounds from its customer and delivers them into the forward contract, receiving:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.7540 = \text{USD }1,754,000
\]</span></p>
<p>Compared with the booked value of USD 1,764,000, the accounting foreign exchange result is:</p>
<p><span class="math display">\[
\text{USD }1,754,000 - \text{USD }1,764,000 = -\text{USD }10,000
\]</span></p>
<p>So Ganado records a <strong>foreign exchange loss of USD 10,000</strong> (about 0.5% loss) relative to the booking date. But notice what it gains is certainty in the exchange.</p>
<p>A fully matched forward hedge is sometimes called:</p>
<ul>
<li><strong>covered</strong>,</li>
<li><strong>perfect</strong>, or</li>
<li><strong>square</strong>.</li>
</ul>
<p>That means the firm already has, or will receive, the exact foreign currency needed to fulfill the forward contract. No residual currency risk remains.</p>
</section>
<section id="money-market-hedge-balance-sheet-hedge" class="level3" data-number="10.4.4">
<h3 data-number="10.4.4" class="anchored" data-anchor-id="money-market-hedge-balance-sheet-hedge"><span class="header-section-number">10.4.4</span> Money Market Hedge (Balance Sheet Hedge)</h3>
<p>A <strong>money market hedge</strong> uses borrowing and spot exchange rather than a forward contract. For a receivable, the firm:</p>
<ol type="1">
<li><strong>borrows the foreign currency today</strong>,</li>
<li><strong>converts it into home currency at the spot rate</strong>, and</li>
<li><strong>repays the foreign-currency loan when the receivable arrives</strong>.</li>
</ol>
<p>Ganado needs a GBP loan whose principal plus interest equals the future receivable of GBP 1,000,000. Since the U.K. 90-day borrowing rate is 2.5%, the amount borrowed today must be:</p>
<p><span class="math display">\[
\frac{\text{GBP }1,000,000}{1+0.025} = \text{GBP }975,610
\]</span></p>
<p>Ganado converts that immediately into dollars at the spot rate:</p>
<p><span class="math display">\[
\text{GBP }975,610 \times \text{USD }1.7640 = \text{USD }1,720,976
\]</span></p>
<p>In 90 days, the GBP receivable of GBP 1,000,000 is used to repay the GBP loan:</p>
<p><span class="math display">\[
\text{GBP }975,610 + \text{GBP }24,390 = \text{GBP }1,000,000
\]</span></p>
<p>So the money market hedge creates a pound liability that offsets the pound asset. That is why it is also called a <strong>balance sheet hedge</strong>.</p>
<p>A simple balance-sheet view looks like this:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Assets</th>
<th>Liabilities and Net Worth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Account receivable: <span class="math display">\[ \text{GBP }1,000,000 \]</span></td>
<td>GBP loan principal: <span class="math display">\[ \text{GBP }975,610 \]</span></td>
</tr>
<tr class="even">
<td></td>
<td>Interest payable: <span class="math display">\[ \text{GBP }24,390 \]</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong>: <span class="math display">\[ \text{GBP }1,000,000 \]</span></td>
<td><strong>Total</strong>: <span class="math display">\[ \text{GBP }1,000,000 \]</span></td>
</tr>
</tbody>
</table>
</section>
<section id="forward-and-money-market-hedges-compared" class="level3" data-number="10.4.5">
<h3 data-number="10.4.5" class="anchored" data-anchor-id="forward-and-money-market-hedges-compared"><span class="header-section-number">10.4.5</span> Forward and Money Market Hedges Compared</h3>
<p>The forward hedge produces dollars in 90 days. The money market hedge produces dollars <strong>today</strong>. So to compare them fairly, the money market hedge proceeds must be carried forward.</p>
<p>Using Ganado’s WACC of 3.0% for the 90-day period,</p>
<p><span class="math display">\[
\text{USD }1,720,976 \times 1.03 = \text{USD }1,772,605
\]</span></p>
<p>This is the future value of the money market hedge proceeds.</p>
<p>Now compare:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Hedge Method</th>
<th style="text-align: right;">Future Value in 90 Days</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forward hedge</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1,754,000 \]</span></td>
</tr>
<tr class="even">
<td>Money market hedge</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1,772,605 \]</span></td>
</tr>
</tbody>
</table>
<p>Under the assumptions in the chapter, the money market hedge is superior.</p>
<section id="break-even-reinvestment-rate" class="level4" data-number="10.4.5.1">
<h4 data-number="10.4.5.1" class="anchored" data-anchor-id="break-even-reinvestment-rate"><span class="header-section-number">10.4.5.1</span> Break-even reinvestment rate</h4>
<p>We can also calculate the break-even investment rate that would make the two methods equivalent.</p>
<p>Set:</p>
<p><span class="math display">\[
\text{Loan proceeds} \times (1+r) = \text{Forward proceeds}
\]</span></p>
<p>So,</p>
<p><span class="math display">\[
\text{USD }1,720,976 \times (1+r) = \text{USD }1,754,000
\]</span></p>
<p>which gives:</p>
<p><span class="math display">\[
r = 0.0192
\]</span></p>
<p>Annualizing over a 360-day year:</p>
<p><span class="math display">\[
0.0192 \times \frac{360}{90} \times 100 = 7.68\%
\]</span></p>
<p>Interpretation:</p>
<ul>
<li>If Ganado can earn <strong>more than 7.68% annualized</strong> on the money market hedge proceeds, the money market hedge dominates.</li>
<li>If it can earn <strong>less than 7.68%</strong>, the forward hedge is preferable.</li>
</ul>
<p>This is an excellent finance insight because it shows that the relative attractiveness of the money market hedge depends on what the firm can do with the dollars received today.</p>
</section>
</section>
<section id="options-market-hedge" class="level3" data-number="10.4.6">
<h3 data-number="10.4.6" class="anchored" data-anchor-id="options-market-hedge"><span class="header-section-number">10.4.6</span> Options Market Hedge</h3>
<p>An <strong>options hedge</strong> gives the firm protection against unfavorable exchange-rate movements while still allowing participation in favorable movements.</p>
<p>Because Ganado has a GBP receivable, it wants a <strong>put option on GBP</strong>. Remember, a <strong>put</strong> is the right (but not the obligation) to sell an asset at a particular price at some point in the future. It can buy a 90-day put on <strong>GBP 1,000,000</strong> with strike price:</p>
<p><span class="math display">\[
\text{USD }1.75 = \text{GBP }1.00
\]</span></p>
<p>and premium of <strong>1.5%</strong>.</p>
<p>The option premium cost today is:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times 0.015 \times \text{USD }1.7640 = \text{USD }26,460
\]</span></p>
<p>Carrying that cost forward 90 days at the WACC of 3%:</p>
<p><span class="math display">\[
\text{USD }26,460 \times 1.03 = \text{USD }27,254
\]</span></p>
<p>So the future value cost of the option is USD 27,254.</p>
<section id="if-the-pound-is-above-the-strike-at-maturity" class="level4" data-number="10.4.6.1">
<h4 data-number="10.4.6.1" class="anchored" data-anchor-id="if-the-pound-is-above-the-strike-at-maturity"><span class="header-section-number">10.4.6.1</span> If the pound is above the strike at maturity</h4>
<p>Suppose the expected spot occurs:</p>
<p><span class="math display">\[
\text{USD }1.7600 = \text{GBP }1.00
\]</span></p>
<p>Ganado lets the put expire and sells pounds in the spot market:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.7600 = \text{USD }1,760,000
\]</span></p>
<p>Net of option cost:</p>
<p><span class="math display">\[
\text{USD }1,760,000 - \text{USD }27,254 = \text{USD }1,732,746
\]</span> <strong>Why do we let the put expire if the price is above the strike price at maturity?</strong></p>
<p>Remember that if the USD goes higher relative to the pound, that means that the dollar is weakening and it takes more dollars to buy 1 GB pound. That is profit for US firms, or at least more USD per GBP.</p>
</section>
<section id="if-the-pound-falls-below-the-strike" class="level4" data-number="10.4.6.2">
<h4 data-number="10.4.6.2" class="anchored" data-anchor-id="if-the-pound-falls-below-the-strike"><span class="header-section-number">10.4.6.2</span> If the pound falls below the strike</h4>
<p>If the pound falls below USD 1.75, Ganado exercises the put and receives:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.75 = \text{USD }1,750,000
\]</span></p>
<p>Net of option cost:</p>
<p><span class="math display">\[
\text{USD }1,750,000 - \text{USD }27,254 = \text{USD }1,722,746
\]</span></p>
<p>So the option hedge sets a <strong>floor</strong> on net proceeds of:</p>
<p><span class="math display">\[
\text{USD }1,722,746
\]</span></p>
<p><strong>That floor is lower than the certainty offered by the forward or money market hedge in this example, but the option preserves upside beyond the strike.</strong></p>
</section>
</section>
<section id="hedging-alternatives-compared" class="level3" data-number="10.4.7">
<h3 data-number="10.4.7" class="anchored" data-anchor-id="hedging-alternatives-compared"><span class="header-section-number">10.4.7</span> Hedging Alternatives Compared</h3>
<p>Ganado’s main alternatives for the GBP receivable can be summarized as follows.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Alternative</th>
<th>Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Remain unhedged</strong></td>
<td>Best upside, worst downside; fully exposed to spot-rate movements</td>
</tr>
<tr class="even">
<td><strong>Forward hedge</strong></td>
<td>Locks in <span class="math display">\[ \text{USD }1,754,000 \]</span></td>
</tr>
<tr class="odd">
<td><strong>Money market hedge</strong></td>
<td>Creates future value of <span class="math display">\[ \text{USD }1,772,605 \]</span> under textbook assumptions</td>
</tr>
<tr class="even">
<td><strong>Put option hedge</strong></td>
<td>Minimum of <span class="math display">\[ \text{USD }1,722,746 \]</span>, but retains upside above strike less option cost</td>
</tr>
</tbody>
</table>
<p>The chapter’s graphical comparison makes two ideas especially clear:</p>
<ol type="1">
<li>If management expects the exchange rate to move <strong>against</strong> the firm, the money market hedge is strongest in this example.</li>
<li>If management expects the exchange rate to move <strong>in favor</strong> of the firm, the option may be attractive because it protects the downside while preserving upside.</li>
</ol>
<p>The choice is therefore not mechanical. It depends on two decision criteria that the firm has to make:</p>
<ol type="1">
<li><strong>The firm’s risk tolerance</strong>, and</li>
<li><strong>Management’s exchange-rate expectation and confidence in that view.</strong></li>
</ol>
</section>
<section id="hedging-an-account-payable" class="level3" data-number="10.4.8">
<h3 data-number="10.4.8" class="anchored" data-anchor-id="hedging-an-account-payable"><span class="header-section-number">10.4.8</span> Hedging an Account Payable</h3>
<p>The logic for a payable is similar, but the mechanics reverse.</p>
<p>If Ganado had to <strong>pay</strong> GBP 1,000,000 in 90 days instead of receiving it, then a stronger pound would be bad news because it would raise the dollar cost of the payment.</p>
<p>The major alternatives are again:</p>
<ul>
<li>remain unhedged,</li>
<li>buy GBP forward,</li>
<li>use a money market hedge, or</li>
<li>buy a call option on GBP.</li>
</ul>
<section id="remain-unhedged" class="level4" data-number="10.4.8.1">
<h4 data-number="10.4.8.1" class="anchored" data-anchor-id="remain-unhedged"><span class="header-section-number">10.4.8.1</span> Remain Unhedged</h4>
<p>If Ganado remains unhedged, it waits 90 days and buys pounds in the spot market when the payment is due.</p>
<p>If the expected spot is:</p>
<p><span class="math display">\[
\text{USD }1.7600 = \text{GBP }1.00
\]</span></p>
<p>then the expected dollar cost is:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.7600 = \text{USD }1,760,000
\]</span></p>
<p>But that cost is uncertain. If the pound rises further, the cost rises. If the pound falls, the cost falls.</p>
</section>
<section id="forward-market-hedge" class="level4" data-number="10.4.8.2">
<h4 data-number="10.4.8.2" class="anchored" data-anchor-id="forward-market-hedge"><span class="header-section-number">10.4.8.2</span> Forward Market Hedge</h4>
<p>To hedge a GBP payable, Ganado must <strong>buy GBP forward</strong>.</p>
<p>At the 90-day forward rate:</p>
<p><span class="math display">\[
\text{USD }1.7540 = \text{GBP }1.00
\]</span></p>
<p>the certain dollar cost becomes:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.7540 = \text{USD }1,754,000
\]</span></p>
<p>This is certain and, in this example, lower than the expected unhedged cost based on the forecast spot rate.</p>
</section>
<section id="money-market-hedge" class="level4" data-number="10.4.8.3">
<h4 data-number="10.4.8.3" class="anchored" data-anchor-id="money-market-hedge"><span class="header-section-number">10.4.8.3</span> Money Market Hedge</h4>
<p>For a payable, the money market hedge reverses direction from the receivable case. Ganado must:</p>
<ol type="1">
<li>buy pounds spot today,</li>
<li>invest them for 90 days in a GBP account, and</li>
<li>use the future pound balance to settle the payable.</li>
</ol>
<p>The pounds needed today are the present value of GBP 1,000,000 discounted at the U.K. 90-day investment rate of 2%:</p>
<p><span class="math display">\[
\frac{\text{GBP }1,000,000}{1.02} = \text{GBP }980,392.16
\]</span></p>
<p>At the spot rate of USD 1.7640 = GBP 1.00, this requires current dollars of:</p>
<p><span class="math display">\[
\text{GBP }980,392.16 \times \text{USD }1.7640 = \text{USD }1,729,411.77
\]</span></p>
<p>To compare this fairly to other methods, carry the current dollar cost forward 90 days using the WACC of 3%:</p>
<p><span class="math display">\[
\text{USD }1,729,411.77 \times 1.03 = \text{USD }1,781,294.12
\]</span></p>
<p>So in this specific example, the money market hedge is more expensive than the forward hedge.</p>
</section>
<section id="option-hedge" class="level4" data-number="10.4.8.4">
<h4 data-number="10.4.8.4" class="anchored" data-anchor-id="option-hedge"><span class="header-section-number">10.4.8.4</span> Option Hedge</h4>
<p>For a payable, the correct option is a <strong>call option on GBP</strong>. As a reminder, a <strong>call</strong> is the right, but not the obligation, to buy and asset, at a set price, sometime in the future.</p>
<p>Ganado can buy a call on <strong>GBP 1,000,000</strong> with strike price:</p>
<p><span class="math display">\[
\text{USD }1.75 = \text{GBP }1.00
\]</span></p>
<p>The premium today is again:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times 0.015 \times \text{USD }1.7640 = \text{USD }26,460
\]</span></p>
<p>Carried forward 90 days at 3%:</p>
<p><span class="math display">\[
\text{USD }26,460 \times 1.03 = \text{USD }27,254
\]</span></p>
<p>If the pound is above the strike at maturity, Ganado exercises the call and buys GBP at USD 1.75. Total maximum dollar cost becomes:</p>
<p><span class="math display">\[
\text{GBP }1,000,000 \times \text{USD }1.75 + \text{USD }27,254 = \text{USD }1,777,254
\]</span></p>
<p>So the call option places a ceiling on the total cost of the payable:</p>
<p><span class="math display">\[
\text{USD }1,777,254
\]</span></p>
<p>If the pound is below the strike at maturity, Ganado lets the call expire and buys GBP in the cheaper spot market, still having paid the premium.</p>
</section>
<section id="strategy-choice" class="level4" data-number="10.4.8.5">
<h4 data-number="10.4.8.5" class="anchored" data-anchor-id="strategy-choice"><span class="header-section-number">10.4.8.5</span> Strategy Choice</h4>
<p>For the account payable case, the chapter’s numbers imply the following ranking under the stated forecast:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alternative</th>
<th style="text-align: right;">Dollar Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forward hedge</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1,754,000 \]</span></td>
</tr>
<tr class="even">
<td>Money market hedge</td>
<td style="text-align: right;"><span class="math display">\[ \text{USD }1,781,294 \]</span></td>
</tr>
<tr class="odd">
<td>Call option hedge</td>
<td style="text-align: right;">Maximum of <span class="math display">\[ \text{USD }1,777,254 \]</span></td>
</tr>
<tr class="even">
<td>Unhedged</td>
<td style="text-align: right;">Uncertain</td>
</tr>
</tbody>
</table>
<p>Given an expected spot of USD 1.76 per pound, the <strong>forward hedge</strong> appears to be the preferred choice in the textbook example.</p>
<p>Again, the general logic is:</p>
<ul>
<li>For a <strong>receivable</strong>, a firm fears depreciation of the foreign currency/appreciation of the home currency and may use a <strong>put</strong> or <strong>sell forward</strong>.</li>
<li>For a <strong>payable</strong>, a firm fears appreciation of the foreign currency/depreciation of the home currency and may use a <strong>call</strong> or <strong>buy forward</strong>.</li>
</ul>
</section>
</section>
</section>
<section id="transaction-exposure-management-in-practice" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="transaction-exposure-management-in-practice"><span class="header-section-number">10.5</span> Transaction Exposure Management in Practice</h2>
<p>The theory of hedging is clean. Practice is not. Firms differ widely in what they hedge, how far out they hedge, how much they hedge, and which instruments they are willing to use.</p>
<p>A key line from the chapter is worth emphasizing: <strong>there are as many different approaches to transaction exposure management as there are firms.</strong></p>
<section id="which-goals" class="level3" data-number="10.5.1">
<h3 data-number="10.5.1" class="anchored" data-anchor-id="which-goals"><span class="header-section-number">10.5.1</span> Which Goals</h3>
<p>Most treasury departments are not structured as profit centers. They are normally viewed as <strong>cost centers</strong> or <strong>service centers</strong>. That means the treasury’s job is not usually to make money by betting on exchange rates. Its job is to protect the firm’s cash flows and support operations.</p>
<p>Common practical goals include:</p>
<ul>
<li>reducing exchange-rate-induced volatility in earnings,</li>
<li>protecting budget rates and operating margins,</li>
<li>increasing predictability of future cash flows,</li>
<li>reducing the chance of financial distress,</li>
<li>supporting debt servicing capacity, and</li>
<li>smoothing reported results.</li>
</ul>
<p>In public companies especially, <strong>earnings smoothing</strong> is often a major objective. Investors prefer more stable and predictable earnings, and firms often believe a sensible hedging program can reduce earnings volatility.</p>
<p>This point also explains why many firms hedge over a horizon linked to budgeting. If the budgeting process is quarterly or annual, treasury often thinks in those same windows.</p>
</section>
<section id="which-transaction-exposures" class="level3" data-number="10.5.2">
<h3 data-number="10.5.2" class="anchored" data-anchor-id="which-transaction-exposures"><span class="header-section-number">10.5.2</span> Which Transaction Exposures</h3>
<p>In practice, firms increasingly hedge not only <strong>existing on-balance-sheet exposures</strong> but also some <strong>anticipated exposures</strong>.</p>
<p>Historically, many firms prohibited hedging anything not yet booked. The logic was conservative:</p>
<ul>
<li>an unbooked transaction may never occur,</li>
<li>but a derivative contract certainly will exist once entered,</li>
<li>so the hedge itself may become an unwanted speculative position if the forecasted transaction disappears.</li>
</ul>
<p>Even so, many firms now hedge highly probable anticipated transactions, especially when they arise from:</p>
<ol type="1">
<li><strong>Contractual exposures</strong> under ongoing commercial agreements, and</li>
<li><strong>Intra-firm transactions</strong> between parent and subsidiary or between subsidiaries.</li>
</ol>
<p>For example, if a company ships to a foreign customer every 90 days under a multi-year supply contract, future receivables are not yet booked, but their likelihood is high. Many firms treat those as hedgeable anticipated exposures.</p>
<p>The same is true for global supply chains. Intra-company shipments and transfer-pricing arrangements often generate regular, predictable cross-border flows. Those too may be hedged.</p>
</section>
<section id="what-levels-of-exposure-cover" class="level3" data-number="10.5.3">
<h3 data-number="10.5.3" class="anchored" data-anchor-id="what-levels-of-exposure-cover"><span class="header-section-number">10.5.3</span> What Levels of Exposure Cover</h3>
<p>Many firms use <strong>proportional hedging policies</strong>. Instead of hedging everything or nothing, they hedge a specified percentage of exposures by currency and maturity.</p>
<p>A typical policy might look like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Maturity Bucket</th>
<th>Typical Cover Policy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-30 days</td>
<td>Very high cover, perhaps 90% to 100%</td>
</tr>
<tr class="even">
<td>30-90 days</td>
<td>Moderate cover, perhaps 50% to 90%</td>
</tr>
<tr class="odd">
<td>More than 90 days</td>
<td>Selective cover or lower required percentage</td>
</tr>
</tbody>
</table>
<p>The logic is sensible:</p>
<ul>
<li>short-dated exposures are more certain and more easily measured, so firms hedge more of them;</li>
<li>long-dated exposures are less certain, more likely to change, and more costly to hedge rigidly.</li>
</ul>
<p>The chapter notes that as maturity lengthens, the required percentage of forward cover often <strong>decreases</strong>, not increases.</p>
<p>A further implication is worth stating clearly: once firms hedge only part of an exposure and then decide selectively what to hedge beyond that, they are implicitly expressing a market view. That is one reason proportional hedging can shade into selective hedging and, at times, into speculation.</p>
</section>
<section id="which-hedging-instruments-and-structures" class="level3" data-number="10.5.4">
<h3 data-number="10.5.4" class="anchored" data-anchor-id="which-hedging-instruments-and-structures"><span class="header-section-number">10.5.4</span> Which Hedging Instruments and Structures</h3>
<p>The Wells Fargo survey summarized in the chapter shows that actual corporate practice is heavily tilted toward <strong>forward contracts</strong>.</p>
<p>A simplified representation of the survey results is:</p>
<section id="hedging-practices" class="level4" data-number="10.5.4.1">
<h4 data-number="10.5.4.1" class="anchored" data-anchor-id="hedging-practices"><span class="header-section-number">10.5.4.1</span> Hedging practices</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Practice</th>
<th style="text-align: right;">Approximate Share of Firms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hedge trade-related exposures</td>
<td style="text-align: right;">70%</td>
</tr>
<tr class="even">
<td>Hedge finance-related exposures</td>
<td style="text-align: right;">67%</td>
</tr>
<tr class="odd">
<td>Hedge forecasted exposures</td>
<td style="text-align: right;">59%</td>
</tr>
<tr class="even">
<td>Hedge net equity investment in subsidiaries</td>
<td style="text-align: right;">10%</td>
</tr>
<tr class="odd">
<td>Hedge net income of subsidiaries</td>
<td style="text-align: right;">8%</td>
</tr>
</tbody>
</table>
</section>
<section id="hedging-instruments" class="level4" data-number="10.5.4.2">
<h4 data-number="10.5.4.2" class="anchored" data-anchor-id="hedging-instruments"><span class="header-section-number">10.5.4.2</span> Hedging instruments</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Instrument</th>
<th style="text-align: right;">Approximate Share of Firms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forward contracts</td>
<td style="text-align: right;">96%</td>
</tr>
<tr class="even">
<td>Options and option combinations</td>
<td style="text-align: right;">20%</td>
</tr>
<tr class="odd">
<td>Cross-currency swaps</td>
<td style="text-align: right;">12%</td>
</tr>
<tr class="even">
<td>Other</td>
<td style="text-align: right;">5%</td>
</tr>
</tbody>
</table>
<p>These numbers are revealing.</p>
<p><strong>Forward contracts dominate practice.</strong> Why?</p>
<ul>
<li>They are simple.</li>
<li>They are familiar.</li>
<li>They require no up-front premium.</li>
<li>They provide certainty.</li>
<li>They fit well with clearly identified receivables and payables.</li>
</ul>
<p><strong>Options are used much less frequently.</strong> Here are three standard reasons:</p>
<ol type="1">
<li><strong>Cost</strong> - premiums can be significant.</li>
<li><strong>Complexity</strong> - many managers prefer simpler instruments.</li>
<li><strong>Bounded protection only</strong> - options protect against one side of the distribution, but not always at the cheapest total cost.</li>
</ol>
<p>On face value, we may assume options are always superior because they preserve upside. In reality, many firms view the premium as too expensive relative to the margin on the underlying sale.</p>
<p>The chapter also notes two practical forward-contract rules seen in many firms:</p>
<ol type="1">
<li>If a forward locks in a favorable accounting or settlement outcome, <strong>100% cover</strong> is often required.</li>
<li>If the forward premium or discount is small, firms are often willing to use a <strong>high level of forward cover</strong>.</li>
</ol>
<p>So the practical conclusion is quite strong:</p>
<p><span class="math display">\[
\text{In real-world treasury practice, forwards remain the primary instrument for transaction exposure management.}
\]</span></p>
<hr>
<p><strong>Key Takeaways for Chapter 10</strong></p>
<ul>
<li>A firm faces <strong>transaction</strong>, <strong>translation</strong>, and <strong>operating</strong> exposure, but transaction exposure is the one most directly tied to already-contracted foreign-currency cash flows.</li>
<li>Hedging generally <strong>reduces risk</strong>, not expected value.</li>
<li>Transaction exposure commonly arises from <strong>foreign-currency receivables, payables, loans, and derivative contracts</strong>.</li>
<li>The major contractual hedges are <strong>forwards, money market hedges, and options</strong>.</li>
<li>For a <strong>receivable</strong>, the firm often sells the foreign currency forward or buys a <strong>put</strong>.</li>
<li>For a <strong>payable</strong>, the firm often buys the foreign currency forward or buys a <strong>call</strong>.</li>
<li>In practice, treasury decisions depend on <strong>risk tolerance, expected exchange-rate movement, hedging cost, and corporate policy</strong>.</li>
<li>Real firms hedge unevenly, but <strong>forward contracts dominate</strong> practice.</li>
</ul>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/clb18\.github\.io\/FIN-4350_International_Finance");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>