project:
  type: website
  resources: 
    - assets/**
  output-dir: docs
  render: 
    - "*.qmd"
    - "lectures/**.qmd"
#    - "!lectures/Chapter05_Lecture**.qmd"
#    - "!lectures/Chapter06_Lecture**.qmd"

    # ==============================
    # SIMULATION RENDER MODE TOGGLE
    # ==============================

    # --- PRIVATE MODE (drafting) ---
#    - "!simulation/**.qmd"

    # --- PUBLIC MODE (release) ---
    - "simulation/**.qmd"

# IMPORTANT:
# When switching simulation modes:
# 1. Delete docs/
# 2. Render website
# 3. Hard refresh browser


website:
  title: "International Finance"
  site-url: "https://clb18.github.io/FIN-4350_International_Finance"
  repo-url: "https://github.com/clb18/FIN-4350_International_Finance"
  
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: CV
        href: cv.qmd

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Lecture Notes"
        contents: lectures

      # ==============================
      # SIMULATION SIDEBAR MODE TOGGLE
      # ==============================

      # --- PRIVATE MODE (hidden) ---
      # (nothing here)

      # --- PUBLIC MODE (visible) ---
      - section: "IF Simulation"
        contents: 
          - text: "Overview - START HERE"
            href: simulation/index.qmd
          - simulation/fx_dashboard_with_trade_tracker.qmd
          - simulation/roles.qmd
          - simulation/countries.qmd
          - simulation/decisions.qmd
          - simulation/deliverables.qmd
          - simulation/trade_fx_options.qmd
          - simulation/Weekly_Brief_sample.qmd
          - simulation/markets.qmd
          - simulation/grading.qmd
          
format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
    css: styles.css
    grid: 
      sidebar-width: 275px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 1.5rem