<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.8.26" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

<meta name="author" content="Prof. Barker" />
<meta name="dcterms.date" content="2025-12-24" />

<title>International Finance - Chapter 1 – International Finance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<!-- htmldependencies:E3FAD763 -->
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css" />
</head>

<body>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">International Finance</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
  aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation"
  onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/syllabus.qmd"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/schedule.qmd"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn"
      data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" 
      aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation"
      onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <h1 class="quarto-secondary-nav-title no-breadcrumbs"></h1>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" role="link"
        aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation"
        onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Lecture Notes</span></span>
  </li>
    </ul>
    </div>
    <div id="quarto-toc-target"></div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" ></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">International Finance - Chapter 1</h1>
<p class="subtitle lead">Multinational Financial Management: Opportunities and Challenges</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof. Barker </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 24, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-opening" id="toc-introduction-and-opening"><span class="header-section-number">1</span> Introduction and Opening</a>
  <ul>
  <li><a href="#welcome-and-context-setting" id="toc-welcome-and-context-setting"><span class="header-section-number">1.1</span> Welcome and Context Setting</a></li>
  <li><a href="#chapter-roadmap" id="toc-chapter-roadmap"><span class="header-section-number">1.2</span> Chapter Roadmap</a></li>
  </ul></li>
  <li><a href="#the-global-financial-marketplace" id="toc-the-global-financial-marketplace"><span class="header-section-number">2</span> The Global Financial Marketplace</a>
  <ul>
  <li><a href="#the-playing-field" id="toc-the-playing-field"><span class="header-section-number">2.1</span> The Playing Field</a>
  <ul>
  <li><a href="#securities-financial-assets" id="toc-securities-financial-assets"><span class="header-section-number">2.1.1</span> Securities (Financial Assets)</a></li>
  <li><a href="#institutions" id="toc-institutions"><span class="header-section-number">2.1.2</span> Institutions</a></li>
  <li><a href="#linkages---the-interbank-market" id="toc-linkages---the-interbank-market"><span class="header-section-number">2.1.3</span> Linkages - The Interbank Market</a></li>
  </ul></li>
  <li><a href="#the-market-for-currencies" id="toc-the-market-for-currencies"><span class="header-section-number">2.2</span> The Market for Currencies</a>
  <ul>
  <li><a href="#important-terminology-discussion" id="toc-important-terminology-discussion"><span class="header-section-number">2.2.1</span> Important Terminology Discussion</a></li>
  </ul></li>
  <li><a href="#calculating-percentage-changes-in-exchange-rates" id="toc-calculating-percentage-changes-in-exchange-rates"><span class="header-section-number">2.3</span> Calculating Percentage Changes in Exchange Rates</a>
  <ul>
  <li><a href="#method-1---foreign-currency-terms-foreign-currency-per-usd" id="toc-method-1---foreign-currency-terms-foreign-currency-per-usd"><span class="header-section-number">2.3.1</span> Method 1 - Foreign Currency Terms (Foreign currency per USD)</a></li>
  <li><a href="#method-2---home-currency-terms-usd-per-foreign-currency" id="toc-method-2---home-currency-terms-usd-per-foreign-currency"><span class="header-section-number">2.3.2</span> Method 2 - Home Currency Terms (USD per foreign currency)</a></li>
  <li><a href="#practice-problem" id="toc-practice-problem"><span class="header-section-number">2.3.3</span> Practice Problem</a></li>
  </ul></li>
  <li><a href="#eurocurrencies-and-the-eurocurrency-market" id="toc-eurocurrencies-and-the-eurocurrency-market"><span class="header-section-number">2.4</span> Eurocurrencies and the Eurocurrency Market</a>
  <ul>
  <li><a href="#historical-origin-fascinating-backstory" id="toc-historical-origin-fascinating-backstory"><span class="header-section-number">2.4.1</span> Historical Origin (Fascinating backstory)</a></li>
  <li><a href="#why-does-this-market-exist-and-thrive" id="toc-why-does-this-market-exist-and-thrive"><span class="header-section-number">2.4.2</span> Why Does This Market Exist and Thrive?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#theory-of-comparative-advantage" id="toc-theory-of-comparative-advantage"><span class="header-section-number">3</span> Theory of Comparative Advantage</a>
  <ul>
  <li><a href="#foundational-economic-theory" id="toc-foundational-economic-theory"><span class="header-section-number">3.1</span> Foundational Economic Theory</a></li>
  <li><a href="#core-concepts" id="toc-core-concepts"><span class="header-section-number">3.2</span> Core Concepts</a>
  <ul>
  <li><a href="#absolute-advantage-adam-smith" id="toc-absolute-advantage-adam-smith"><span class="header-section-number">3.2.1</span> Absolute Advantage (Adam Smith)</a></li>
  <li><a href="#comparative-advantage-david-ricardo" id="toc-comparative-advantage-david-ricardo"><span class="header-section-number">3.2.2</span> Comparative Advantage (David Ricardo)</a></li>
  <li><a href="#simple-example" id="toc-simple-example"><span class="header-section-number">3.2.3</span> Simple Example</a></li>
  </ul></li>
  <li><a href="#modern-reality-vs.-theory" id="toc-modern-reality-vs.-theory"><span class="header-section-number">3.3</span> Modern Reality vs. Theory</a>
  <ul>
  <li><a href="#government-interference" id="toc-government-interference"><span class="header-section-number">3.3.1</span> Government Interference</a></li>
  <li><a href="#factor-mobility" id="toc-factor-mobility"><span class="header-section-number">3.3.2</span> Factor Mobility</a></li>
  <li><a href="#more-complex-factors-of-production" id="toc-more-complex-factors-of-production"><span class="header-section-number">3.3.3</span> More Complex Factors of Production</a></li>
  <li><a href="#comparative-advantage-shifts-over-time" id="toc-comparative-advantage-shifts-over-time"><span class="header-section-number">3.3.4</span> Comparative Advantage Shifts Over Time</a></li>
  </ul></li>
  <li><a href="#relevance-today" id="toc-relevance-today"><span class="header-section-number">3.4</span> Relevance Today</a></li>
  </ul></li>
  <li><a href="#what-makes-international-finance-different-15-minutes" id="toc-what-makes-international-finance-different-15-minutes"><span class="header-section-number">4</span> What Makes International Finance Different? (15 minutes)</a>
  <ul>
  <li><a href="#framework-for-understanding-differences" id="toc-framework-for-understanding-differences"><span class="header-section-number">4.1</span> Framework for Understanding Differences</a></li>
  <li><a href="#culture-history-and-institutional-differences" id="toc-culture-history-and-institutional-differences"><span class="header-section-number">4.2</span> Culture, History, and Institutional Differences</a>
  <ul>
  <li><a href="#cultural-challenges" id="toc-cultural-challenges"><span class="header-section-number">4.2.1</span> Cultural Challenges</a></li>
  <li><a href="#historical-context" id="toc-historical-context"><span class="header-section-number">4.2.2</span> Historical Context</a></li>
  <li><a href="#institutional-frameworks" id="toc-institutional-frameworks"><span class="header-section-number">4.2.3</span> Institutional Frameworks</a></li>
  </ul></li>
  <li><a href="#corporate-governance-differences" id="toc-corporate-governance-differences"><span class="header-section-number">4.3</span> Corporate Governance Differences</a>
  <ul>
  <li><a href="#three-primary-models" id="toc-three-primary-models"><span class="header-section-number">4.3.1</span> Three Primary Models</a></li>
  </ul></li>
  <li><a href="#foreign-exchange-risk" id="toc-foreign-exchange-risk"><span class="header-section-number">4.4</span> Foreign Exchange Risk</a>
  <ul>
  <li><a href="#types-of-foreign-exchange-exposure" id="toc-types-of-foreign-exchange-exposure"><span class="header-section-number">4.4.1</span> Types of Foreign Exchange Exposure</a></li>
  <li><a href="#classroom-example-ganado-corporation" id="toc-classroom-example-ganado-corporation"><span class="header-section-number">4.4.2</span> Classroom Example: Ganado Corporation</a></li>
  </ul></li>
  <li><a href="#political-risk" id="toc-political-risk"><span class="header-section-number">4.5</span> Political Risk</a>
  <ul>
  <li><a href="#types-of-political-risk" id="toc-types-of-political-risk"><span class="header-section-number">4.5.1</span> Types of Political Risk</a></li>
  </ul></li>
  <li><a href="#modifications-to-financial-theory" id="toc-modifications-to-financial-theory"><span class="header-section-number">4.6</span> Modifications to Financial Theory</a>
  <ul>
  <li><a href="#cost-of-capital" id="toc-cost-of-capital"><span class="header-section-number">4.6.1</span> Cost of Capital</a></li>
  <li><a href="#capital-budgeting" id="toc-capital-budgeting"><span class="header-section-number">4.6.2</span> Capital Budgeting</a></li>
  <li><a href="#working-capital-management" id="toc-working-capital-management"><span class="header-section-number">4.6.3</span> Working Capital Management</a></li>
  <li><a href="#capital-structure" id="toc-capital-structure"><span class="header-section-number">4.6.4</span> Capital Structure</a></li>
  </ul></li>
  <li><a href="#modified-financial-instruments" id="toc-modified-financial-instruments"><span class="header-section-number">4.7</span> Modified Financial Instruments</a>
  <ul>
  <li><a href="#currency-derivatives" id="toc-currency-derivatives"><span class="header-section-number">4.7.1</span> Currency Derivatives</a></li>
  <li><a href="#interest-rate-instruments" id="toc-interest-rate-instruments"><span class="header-section-number">4.7.2</span> Interest Rate Instruments</a></li>
  <li><a href="#trade-finance-instruments" id="toc-trade-finance-instruments"><span class="header-section-number">4.7.3</span> Trade Finance Instruments</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#the-globalization-process" id="toc-the-globalization-process"><span class="header-section-number">5</span> The Globalization Process</a>
  <ul>
  <li><a href="#introducing-ganado-corporation" id="toc-introducing-ganado-corporation"><span class="header-section-number">5.1</span> Introducing Ganado Corporation</a>
  <ul>
  <li><a href="#background" id="toc-background"><span class="header-section-number">5.1.1</span> Background</a></li>
  </ul></li>
  <li><a href="#phase-1-domestic-to-international-trade" id="toc-phase-1-domestic-to-international-trade"><span class="header-section-number">5.2</span> Phase 1: Domestic to International Trade</a>
  <ul>
  <li><a href="#domestic-phase-characteristics" id="toc-domestic-phase-characteristics"><span class="header-section-number">5.2.1</span> Domestic Phase Characteristics</a></li>
  <li><a href="#catalyst-for-change" id="toc-catalyst-for-change"><span class="header-section-number">5.2.2</span> Catalyst for Change</a></li>
  <li><a href="#international-trade-phase" id="toc-international-trade-phase"><span class="header-section-number">5.2.3</span> International Trade Phase</a></li>
  <li><a href="#two-new-major-challenges" id="toc-two-new-major-challenges"><span class="header-section-number">5.2.4</span> Two New Major Challenges</a></li>
  </ul></li>
  <li><a href="#phase-2-international-trade-to-multinational-enterprise" id="toc-phase-2-international-trade-to-multinational-enterprise"><span class="header-section-number">5.3</span> Phase 2: International Trade to Multinational Enterprise</a>
  <ul>
  <li><a href="#why-make-this-leap" id="toc-why-make-this-leap"><span class="header-section-number">5.3.1</span> Why Make This Leap?</a></li>
  </ul></li>
  <li><a href="#the-foreign-direct-investment-spectrum" id="toc-the-foreign-direct-investment-spectrum"><span class="header-section-number">5.4</span> The Foreign Direct Investment Spectrum</a>
  <ul>
  <li><a href="#increasing-foreign-presence-low-to-high" id="toc-increasing-foreign-presence-low-to-high"><span class="header-section-number">5.4.1</span> Increasing Foreign Presence (Low to High)</a></li>
  </ul></li>
  <li><a href="#consolidation-challenges" id="toc-consolidation-challenges"><span class="header-section-number">5.5</span> Consolidation Challenges</a>
  <ul>
  <li><a href="#the-problem" id="toc-the-problem"><span class="header-section-number">5.5.1</span> The Problem</a></li>
  <li><a href="#the-process" id="toc-the-process"><span class="header-section-number">5.5.2</span> The Process</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#limits-to-financial-globalization-8-minutes" id="toc-limits-to-financial-globalization-8-minutes"><span class="header-section-number">6</span> Limits to Financial Globalization (8 minutes)</a>
  <ul>
  <li><a href="#not-all-globalization-is-inevitable-or-beneficial" id="toc-not-all-globalization-is-inevitable-or-beneficial"><span class="header-section-number">6.1</span> Not All Globalization is Inevitable or Beneficial</a></li>
  <li><a href="#the-twin-agency-problems" id="toc-the-twin-agency-problems"><span class="header-section-number">6.2</span> The “Twin Agency Problems”</a>
  <ul>
  <li><a href="#first-agency-problem---corporate-insiders" id="toc-first-agency-problem---corporate-insiders"><span class="header-section-number">6.2.1</span> First Agency Problem - Corporate Insiders</a></li>
  <li><a href="#second-agency-problem---governmentsovereign-insiders" id="toc-second-agency-problem---governmentsovereign-insiders"><span class="header-section-number">6.2.2</span> Second Agency Problem - Government/Sovereign Insiders</a></li>
  </ul></li>
  <li><a href="#consequences-for-global-capital-flows" id="toc-consequences-for-global-capital-flows"><span class="header-section-number">6.3</span> Consequences for Global Capital Flows</a>
  <ul>
  <li><a href="#real-world-examples" id="toc-real-world-examples"><span class="header-section-number">6.3.1</span> Real-World Examples</a></li>
  </ul></li>
  <li><a href="#contemporary-challenges" id="toc-contemporary-challenges"><span class="header-section-number">6.4</span> Contemporary Challenges</a>
  <ul>
  <li><a href="#three-current-issues" id="toc-three-current-issues"><span class="header-section-number">6.4.1</span> Three Current Issues</a></li>
  </ul></li>
  <li><a href="#the-path-forward" id="toc-the-path-forward"><span class="header-section-number">6.5</span> The Path Forward</a></li>
  </ul></li>
  <li><a href="#conclusion-and-synthesis-5-minutes" id="toc-conclusion-and-synthesis-5-minutes"><span class="header-section-number">7</span> Conclusion and Synthesis (5 minutes)</a>
  <ul>
  <li><a href="#connecting-the-dots" id="toc-connecting-the-dots"><span class="header-section-number">7.1</span> Connecting the Dots</a>
  <ul>
  <li><a href="#the-global-financial-marketplace-1" id="toc-the-global-financial-marketplace-1"><span class="header-section-number">7.1.1</span> The Global Financial Marketplace</a></li>
  <li><a href="#comparative-advantage" id="toc-comparative-advantage"><span class="header-section-number">7.1.2</span> Comparative Advantage</a></li>
  <li><a href="#what-makes-international-finance-unique" id="toc-what-makes-international-finance-unique"><span class="header-section-number">7.1.3</span> What Makes International Finance Unique</a></li>
  <li><a href="#the-globalization-journey" id="toc-the-globalization-journey"><span class="header-section-number">7.1.4</span> The Globalization Journey</a></li>
  <li><a href="#limits-and-challenges" id="toc-limits-and-challenges"><span class="header-section-number">7.1.5</span> Limits and Challenges</a></li>
  </ul></li>
  <li><a href="#looking-ahead" id="toc-looking-ahead"><span class="header-section-number">7.2</span> Looking Ahead</a></li>
  <li><a href="#why-this-matters-to-you" id="toc-why-this-matters-to-you"><span class="header-section-number">7.3</span> Why This Matters to You</a>
  <ul>
  <li><a href="#career-relevance" id="toc-career-relevance"><span class="header-section-number">7.3.1</span> Career Relevance</a></li>
  <li><a href="#citizenship" id="toc-citizenship"><span class="header-section-number">7.3.2</span> Citizenship</a></li>
  <li><a href="#personal-finance" id="toc-personal-finance"><span class="header-section-number">7.3.3</span> Personal Finance</a></li>
  </ul></li>
  <li><a href="#practical-advice-for-success-in-this-course" id="toc-practical-advice-for-success-in-this-course"><span class="header-section-number">7.4</span> Practical Advice for Success in This Course</a>
  <ul>
  <li><a href="#stay-current" id="toc-stay-current"><span class="header-section-number">7.4.1</span> Stay Current</a></li>
  <li><a href="#think-critically" id="toc-think-critically"><span class="header-section-number">7.4.2</span> Think Critically</a></li>
  <li><a href="#connect-concepts" id="toc-connect-concepts"><span class="header-section-number">7.4.3</span> Connect Concepts</a></li>
  <li><a href="#use-real-examples" id="toc-use-real-examples"><span class="header-section-number">7.4.4</span> Use Real Examples</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#questions-and-discussion-5-10-minutes" id="toc-questions-and-discussion-5-10-minutes"><span class="header-section-number">8</span> Questions and Discussion (5-10 minutes)</a>
  <ul>
  <li><a href="#check-for-understanding" id="toc-check-for-understanding"><span class="header-section-number">8.1</span> Check for Understanding</a></li>
  <li><a href="#preview-next-class" id="toc-preview-next-class"><span class="header-section-number">8.2</span> Preview Next Class</a></li>
  </ul></li>
  <li><a href="#final-thoughts-2-minutes" id="toc-final-thoughts-2-minutes"><span class="header-section-number">9</span> Final Thoughts (2 minutes)</a></li>
  </ul>
</nav>
<section id="introduction-and-opening" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction and Opening</h1>
<section id="welcome-and-context-setting" class="level2" data-number="1.1">
<h2 data-number="1.1"><span class="header-section-number">1.1</span> Welcome and Context Setting</h2>
<p>Today we begin our journey into the fascinating world of international finance by exploring what makes multinational financial management both uniquely challenging and remarkably rewarding.</p>
<p><strong>Opening Question to Class:</strong> “How many of you have used a product today that was made by a company operating in multiple countries?”</p>
<p>This simple exercise demonstrates that we live in a deeply interconnected global economy. The phone in your pocket, the coffee you drank this morning, the streaming service you use - all likely involve multinational enterprises (MNEs) managing complex financial operations across borders.</p>
</section>
<section id="chapter-roadmap" class="level2" data-number="1.2">
<h2 data-number="1.2"><span class="header-section-number">1.2</span> Chapter Roadmap</h2>
<p>Today we’ll cover four major learning objectives:</p>
<ol type="1">
<li><strong>The Global Financial Marketplace</strong> - Understanding the players, institutions, and linkages</li>
<li><strong>Theory of Comparative Advantage</strong> - Why international trade and investment make economic sense</li>
<li><strong>What Makes International Finance Different</strong> - The unique challenges MNEs face</li>
<li><strong>The Globalization Process</strong> - How companies evolve from domestic to truly global operations</li>
</ol>
<hr />
</section>
</section>
<section id="the-global-financial-marketplace" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The Global Financial Marketplace</h1>
<section id="the-playing-field" class="level2" data-number="2.1">
<h2 data-number="2.1"><span class="header-section-number">2.1</span> The Playing Field</h2>
<p>Think of the global financial marketplace as a complex ecosystem with three fundamental components:</p>
<section id="securities-financial-assets" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1"><span class="header-section-number">2.1.1</span> Securities (Financial Assets)</h3>
<ul>
<li>At the foundation are government debt securities - US Treasury Bonds, UK gilts, German bunds</li>
<li>These “risk-free” securities form the benchmark for pricing all other assets</li>
<li>Built upon this foundation: corporate bonds, equities (stocks), bank loans</li>
<li>More recently: derivatives - financial instruments whose value derives from underlying assets</li>
</ul>
<p><strong>Critical Point:</strong> The health of the global financial system depends on the quality of these securities. When securities fail (remember the 2008 financial crisis with mortgage-backed securities), the entire system suffers.</p>
</section>
<section id="institutions" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2"><span class="header-section-number">2.1.2</span> Institutions</h3>
<ul>
<li><strong>Central Banks</strong>: Create and control money supply (Federal Reserve, European Central Bank, Bank of Japan)</li>
<li><strong>Commercial Banks</strong>: Take deposits and extend loans both domestically and internationally</li>
<li><strong>Investment Banks &amp; Financial Institutions</strong>: Trade securities, facilitate capital flows, create financial products</li>
</ul>
</section>
<section id="linkages---the-interbank-market" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3"><span class="header-section-number">2.1.3</span> Linkages - The Interbank Market</h3>
<ul>
<li>This is the “plumbing” of the global financial system</li>
<li>Uses CURRENCY as the medium of exchange</li>
<li>Historically centered on LIBOR (London Interbank Offered Rate)</li>
<li><strong>Important note:</strong> LIBOR is being phased out and replaced (we’ll study this in Chapter 8)</li>
</ul>
</section>
</section>
<section id="the-market-for-currencies" class="level2" data-number="2.2">
<h2 data-number="2.2"><span class="header-section-number">2.2</span> The Market for Currencies</h2>
<p><strong>Key Concept:</strong> A foreign exchange rate is simply the price of one currency in terms of another.</p>
<p><strong>Example:</strong></p>
<pre><code>EUR 1.00 = USD 1.1274
or
USD 1.1274 = EUR 1.00</code></pre>
<section id="important-terminology-discussion" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1"><span class="header-section-number">2.2.1</span> Important Terminology Discussion</h3>
<p>Let me address something that often confuses students - currency quotation conventions. There are different ways to express the same exchange rate:</p>
<ul>
<li><strong>Traditional notation</strong>: $1.1274/€ (read as “1.1274 dollars per euro”)</li>
<li><strong>ISO code format</strong>: USD1.1274 = EUR1.00</li>
<li><strong>Financial press variations</strong>:
<ul>
<li>EUR/USD 1.1274</li>
<li>EUR-USD 1.1274</li>
<li>EURUSD 1.1274</li>
</ul></li>
</ul>
<p>All mean the same thing! The key is understanding which currency is the “base” (the one that equals 1.00) and which is the “quote” (the price).</p>
<p><strong>Convention to Remember:</strong></p>
<ul>
<li>EUR, GBP (British pound), and some Commonwealth currencies are typically quoted as “dollars per foreign currency”</li>
<li>Most other currencies quote as “foreign currency per dollar”</li>
</ul>
<p><strong>Why does this matter?</strong> Because when you calculate percentage changes or returns, you need to know which currency is in the numerator and which is in the denominator.</p>
</section>
</section>
<section id="calculating-percentage-changes-in-exchange-rates" class="level2" data-number="2.3">
<h2 data-number="2.3"><span class="header-section-number">2.3</span> Calculating Percentage Changes in Exchange Rates</h2>
<p><strong>This is critical - pay close attention.</strong></p>
<p>Let’s work through the Argentine peso example from your textbook:</p>
<p><strong>Scenario:</strong> December 16, 2015 - Argentina lifts currency controls</p>
<ul>
<li>Beginning rate: ARG 9.7908 = USD 1.00</li>
<li>Ending rate: ARG 13.6160 = USD 1.00</li>
</ul>
<p><strong>Question:</strong> What happened to the peso’s value?</p>
<section id="method-1---foreign-currency-terms-foreign-currency-per-usd" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1"><span class="header-section-number">2.3.1</span> Method 1 - Foreign Currency Terms (Foreign currency per USD)</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb2"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Given exchange rates</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>begin_rate <span class="ot">&lt;-</span> <span class="fl">9.7908</span>  <span class="co"># ARG per USD</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>end_rate <span class="ot">&lt;-</span> <span class="fl">13.6160</span>   <span class="co"># ARG per USD</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage change</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>pct_change_method1 <span class="ot">&lt;-</span> ((begin_rate <span class="sc">-</span> end_rate) <span class="sc">/</span> end_rate) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Method 1 Calculation:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Method 1 Calculation:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb4"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Beginning rate: ARG&quot;</span>, begin_rate, <span class="st">&quot;= USD 1.00</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Beginning rate: ARG 9.7908 = USD 1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb6"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Ending rate: ARG&quot;</span>, end_rate, <span class="st">&quot;= USD 1.00</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Ending rate: ARG 13.616 = USD 1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Percentage change:&quot;</span>, <span class="fu">round</span>(pct_change_method1, <span class="dv">2</span>), <span class="st">&quot;%</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage change: -28.09 %</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> The peso FELL 28% in value. Notice:</p>
<ul>
<li>It takes MORE pesos to buy one dollar (went from 9.79 to 13.62)</li>
<li>The calculation yielded a NEGATIVE number</li>
<li>Both indicate depreciation</li>
</ul>
</section>
<section id="method-2---home-currency-terms-usd-per-foreign-currency" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2"><span class="header-section-number">2.3.2</span> Method 2 - Home Currency Terms (USD per foreign currency)</h3>
<p>First, we need to flip the rates:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb10"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to USD per ARG</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>begin_rate_usd <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> begin_rate</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>end_rate_usd <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> end_rate</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage change</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>pct_change_method2 <span class="ot">&lt;-</span> ((end_rate_usd <span class="sc">-</span> begin_rate_usd) <span class="sc">/</span> begin_rate_usd) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Method 2 Calculation:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Method 2 Calculation:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb12"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Beginning rate: USD&quot;</span>, <span class="fu">round</span>(begin_rate_usd, <span class="dv">5</span>), <span class="st">&quot;= ARG 1.00</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Beginning rate: USD 0.10214 = ARG 1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb14"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Ending rate: USD&quot;</span>, <span class="fu">round</span>(end_rate_usd, <span class="dv">5</span>), <span class="st">&quot;= ARG 1.00</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Ending rate: USD 0.07344 = ARG 1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Percentage change:&quot;</span>, <span class="fu">round</span>(pct_change_method2, <span class="dv">2</span>), <span class="st">&quot;%</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage change: -28.09 %</code></pre>
</div>
</div>
<p><strong>Same answer!</strong> The peso fell 28%.</p>
<p><strong>Teaching Point:</strong> Many students find Method 2 more intuitive because it follows the standard “end minus beginning over beginning” formula. However, both methods MUST give the same answer.</p>
</section>
<section id="practice-problem" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3"><span class="header-section-number">2.3.3</span> Practice Problem</h3>
<p>If the Mexican peso changes from MXN 16.00 = USD 1.00 to MXN 20.00 = USD 1.00, what is the percentage change?</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb18"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mexican peso example</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mxn_begin <span class="ot">&lt;-</span> <span class="fl">16.00</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>mxn_end <span class="ot">&lt;-</span> <span class="fl">20.00</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage change</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>mxn_pct_change <span class="ot">&lt;-</span> ((mxn_begin <span class="sc">-</span> mxn_end) <span class="sc">/</span> mxn_end) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Mexican Peso Change:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Mexican Peso Change:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb20"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Answer:&quot;</span>, <span class="fu">round</span>(mxn_pct_change, <span class="dv">2</span>), <span class="st">&quot;%</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Answer: -20 %</code></pre>
</div>
</div>
</section>
</section>
<section id="eurocurrencies-and-the-eurocurrency-market" class="level2" data-number="2.4">
<h2 data-number="2.4"><span class="header-section-number">2.4</span> Eurocurrencies and the Eurocurrency Market</h2>
<p><strong>Critical Definition:</strong> Eurocurrencies are deposits of a currency held in banks OUTSIDE that currency’s home country.</p>
<p><strong>Examples:</strong></p>
<ul>
<li><strong>Eurodollars</strong>: US dollars deposited in a London bank</li>
<li><strong>Euroyen</strong>: Japanese yen deposited in a Singapore bank</li>
<li><strong>Eurosterling</strong>: British pounds deposited in a Paris bank</li>
</ul>
<p><strong>Important:</strong> The “euro” prefix has NOTHING to do with the European currency. This terminology predates the euro.</p>
<section id="historical-origin-fascinating-backstory" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1"><span class="header-section-number">2.4.1</span> Historical Origin (Fascinating backstory)</h3>
<ul>
<li>Born after WWII</li>
<li>Soviet Union and Eastern European countries held US dollars</li>
<li>Feared US government might freeze these dollar assets</li>
<li>Deposited dollars in European banks instead (particularly in London)</li>
<li>The market grew from there</li>
</ul>
</section>
<section id="why-does-this-market-exist-and-thrive" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2"><span class="header-section-number">2.4.2</span> Why Does This Market Exist and Thrive?</h3>
<ol type="1">
<li><strong>Regulatory Arbitrage</strong>: Fewer regulations than domestic banking
<ul>
<li>No reserve requirements</li>
<li>No deposit insurance costs (like FDIC in the US)</li>
<li>Less bureaucratic overhead</li>
</ul></li>
<li><strong>Narrow Spreads</strong>: The difference between deposit and loan rates is often less than 1%
<ul>
<li>Why? Wholesale market (large transactions, $500,000+)</li>
<li>Creditworthy borrowers (corporations, governments)</li>
<li>Lower overhead costs</li>
</ul></li>
<li><strong>Two Primary Functions</strong>:
<ul>
<li><strong>Money market device</strong>: Corporations park excess cash, earning higher interest than domestic alternatives</li>
<li><strong>Lending source</strong>: Companies borrow for working capital, trade finance</li>
</ul></li>
</ol>
<p><strong>LIBOR Connection:</strong> The London Interbank Offered Rate (LIBOR) is the benchmark interest rate for the eurocurrency market. It represents the rate at which banks lend to each other in London.</p>
<p><strong>Current Developments:</strong> LIBOR is being replaced due to manipulation scandals. We’ll explore this transition in detail in Chapter 8.</p>
<hr />
</section>
</section>
</section>
<section id="theory-of-comparative-advantage" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Theory of Comparative Advantage</h1>
<section id="foundational-economic-theory" class="level2" data-number="3.1">
<h2 data-number="3.1"><span class="header-section-number">3.1</span> Foundational Economic Theory</h2>
<p><strong>Question to class:</strong> “Why do countries trade with each other?”</p>
<p>The theory of comparative advantage, developed by David Ricardo in 1817 (building on Adam Smith’s work from 1776), provides the intellectual foundation for understanding international trade and investment.</p>
</section>
<section id="core-concepts" class="level2" data-number="3.2">
<h2 data-number="3.2"><span class="header-section-number">3.2</span> Core Concepts</h2>
<section id="absolute-advantage-adam-smith" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1"><span class="header-section-number">3.2.1</span> Absolute Advantage (Adam Smith)</h3>
<ul>
<li>A country should specialize in producing goods it can make most efficiently</li>
<li>Trade these for goods other countries make more efficiently</li>
<li>Result: More total production, lower prices, higher quality of life</li>
</ul>
</section>
<section id="comparative-advantage-david-ricardo" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2"><span class="header-section-number">3.2.2</span> Comparative Advantage (David Ricardo)</h3>
<ul>
<li>Even if one country has absolute advantage in producing EVERYTHING, both countries benefit from specialization</li>
<li>Each country should specialize in what it does RELATIVELY better</li>
<li>The key word is “comparative” - relative, not absolute</li>
</ul>
</section>
<section id="simple-example" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3"><span class="header-section-number">3.2.3</span> Simple Example</h3>
<p>Imagine two countries - the US and China:</p>
<ul>
<li>US: Can produce either 100 computers OR 100 bushels of wheat with the same resources</li>
<li>China: Can produce either 50 computers OR 150 bushels of wheat with the same resources</li>
</ul>
<p>Even though the US has absolute advantage in computers, China might still have comparative advantage in wheat production if the opportunity costs differ appropriately.</p>
</section>
</section>
<section id="modern-reality-vs.-theory" class="level2" data-number="3.3">
<h2 data-number="3.3"><span class="header-section-number">3.3</span> Modern Reality vs. Theory</h2>
<p>The textbook presents important limitations to pure comparative advantage theory:</p>
<section id="government-interference" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1"><span class="header-section-number">3.3.1</span> Government Interference</h3>
<ul>
<li>Tariffs and quotas</li>
<li>Subsidies to domestic industries</li>
<li>Political motivations (food security, defense industries, employment goals)</li>
</ul>
<p><strong>Example:</strong> Many countries protect their agricultural sectors even when they’re not the most efficient producers, because food security is considered a national security issue.</p>
</section>
<section id="factor-mobility" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2"><span class="header-section-number">3.3.2</span> Factor Mobility</h3>
<ul>
<li>Classical theory assumed factors of production (land, labor, capital) stayed within countries</li>
<li>Modern reality: Capital flows freely across borders</li>
<li>Technology transfers rapidly</li>
<li>Even labor moves (though less freely than capital)</li>
</ul>
</section>
<section id="more-complex-factors-of-production" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3"><span class="header-section-number">3.3.3</span> More Complex Factors of Production</h3>
<p>Modern location decisions consider:</p>
<ul>
<li>Managerial expertise</li>
<li>Legal and regulatory environment</li>
<li>R&amp;D capabilities</li>
<li>Education levels of workforce</li>
<li>Infrastructure quality</li>
<li>Access to capital markets</li>
<li>Tax differentials</li>
<li>Political stability</li>
</ul>
</section>
<section id="comparative-advantage-shifts-over-time" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4"><span class="header-section-number">3.3.4</span> Comparative Advantage Shifts Over Time</h3>
<p><strong>Powerful Example from Textbook:</strong></p>
<p>Cotton textile production comparative advantage has shifted over 150 years:</p>
<ul>
<li>United Kingdom (1800s) → United States (early 1900s) → Japan (mid-1900s) → Hong Kong → Taiwan → China (present)</li>
</ul>
<p>This illustrates how comparative advantage is dynamic, not static.</p>
</section>
</section>
<section id="relevance-today" class="level2" data-number="3.4">
<h2 data-number="3.4"><span class="header-section-number">3.4</span> Relevance Today</h2>
<p>Despite limitations, comparative advantage remains highly relevant:</p>
<p><strong>Modern Application:</strong> Service outsourcing and the global supply chain</p>
<ul>
<li>Financial back offices in Manila (Philippines)</li>
<li>IT engineering in Hungary and India</li>
<li>Manufacturing in Vietnam and Bangladesh</li>
<li>Design and innovation in Silicon Valley</li>
</ul>
<p><strong>Key Insight:</strong> Modern comparative advantage is based on:</p>
<ul>
<li>Labor skills and costs</li>
<li>Access to capital</li>
<li>Technology and innovation capacity</li>
<li>Telecommunications infrastructure</li>
</ul>
<p><strong>Question for Discussion:</strong> “Can you think of services or products where the US maintains comparative advantage?”</p>
<p>(Expected answers: innovation, higher education, entertainment, certain high-tech manufacturing)</p>
<hr />
</section>
</section>
<section id="what-makes-international-finance-different-15-minutes" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> What Makes International Finance Different? (15 minutes)</h1>
<section id="framework-for-understanding-differences" class="level2" data-number="4.1">
<h2 data-number="4.1"><span class="header-section-number">4.1</span> Framework for Understanding Differences</h2>
<p>International financial management differs from domestic finance in six key dimensions:</p>
</section>
<section id="culture-history-and-institutional-differences" class="level2" data-number="4.2">
<h2 data-number="4.2"><span class="header-section-number">4.2</span> Culture, History, and Institutional Differences</h2>
<section id="cultural-challenges" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1"><span class="header-section-number">4.2.1</span> Cultural Challenges</h3>
<ul>
<li>Business practices vary enormously</li>
<li>Contract interpretation differences</li>
<li>Relationship vs. transaction orientation</li>
<li>Time orientation (short-term vs. long-term)</li>
</ul>
<p><strong>Example:</strong> In many Asian business cultures, building relationships (guanxi in China) is prerequisite to doing business. In the US, contracts often precede relationships.</p>
</section>
<section id="historical-context" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2"><span class="header-section-number">4.2.2</span> Historical Context</h3>
<ul>
<li>Legal systems differ (common law vs. civil law vs. religious law)</li>
<li>Accounting standards vary (though IFRS is harmonizing some)</li>
<li>Property rights protection differs dramatically</li>
</ul>
</section>
<section id="institutional-frameworks" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3"><span class="header-section-number">4.2.3</span> Institutional Frameworks</h3>
<ul>
<li>Banking system structures</li>
<li>Capital market development levels</li>
<li>Government roles in economy</li>
<li>Corruption and governance quality</li>
</ul>
<p><strong>Real World Impact:</strong> A company expanding to a new country must understand these differences. What works in New York may fail in Mumbai or Moscow - not because the financial principles are different, but because the operating environment is different.</p>
</section>
</section>
<section id="corporate-governance-differences" class="level2" data-number="4.3">
<h2 data-number="4.3"><span class="header-section-number">4.3</span> Corporate Governance Differences</h2>
<p><strong>Critical Point:</strong> Not all countries have the same ownership structures or governance models.</p>
<section id="three-primary-models" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1"><span class="header-section-number">4.3.1</span> Three Primary Models</h3>
<p><strong>1. Anglo-American Model:</strong></p>
<ul>
<li>Dispersed shareholders</li>
<li>Active stock markets</li>
<li>Strong shareholder rights</li>
<li>Goal: Maximize shareholder value</li>
<li>Examples: US, UK, Canada, Australia</li>
</ul>
<p><strong>2. Continental European Model:</strong></p>
<ul>
<li>Concentrated ownership (families, banks, other corporations)</li>
<li>Stakeholder orientation (employees, community, shareholders)</li>
<li>Bank-centered finance</li>
<li>Examples: Germany, France, Italy</li>
</ul>
<p><strong>3. Asian Model:</strong></p>
<ul>
<li>Often family-controlled (even in public companies)</li>
<li>Keiretsu in Japan, Chaebol in Korea</li>
<li>Network relationships important</li>
<li>State ownership common (especially China)</li>
</ul>
<p><strong>Why This Matters:</strong></p>
<ul>
<li>Affects access to capital</li>
<li>Influences financial decisions</li>
<li>Determines accountability structures</li>
<li>Shapes strategic objectives</li>
</ul>
</section>
</section>
<section id="foreign-exchange-risk" class="level2" data-number="4.4">
<h2 data-number="4.4"><span class="header-section-number">4.4</span> Foreign Exchange Risk</h2>
<p><strong>This is THE defining characteristic of international finance.</strong></p>
<ul>
<li><strong>Domestic firm:</strong> All transactions in one currency</li>
<li><strong>International trading firm:</strong> Some transactions in foreign currencies (import/export)</li>
<li><strong>Multinational firm:</strong> Extensive foreign currency exposure through:
<ul>
<li>Foreign sales and revenues</li>
<li>Foreign costs and expenses<br />
</li>
<li>Foreign assets and liabilities</li>
<li>Foreign subsidiary operations</li>
</ul></li>
</ul>
<section id="types-of-foreign-exchange-exposure" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1"><span class="header-section-number">4.4.1</span> Types of Foreign Exchange Exposure</h3>
<p><strong>1. Transaction Exposure:</strong></p>
<ul>
<li>Committed but not yet settled foreign currency transactions</li>
<li>Example: US company sells to German customer, invoice for €1 million due in 90 days</li>
<li>Risk: Euro value could fall during 90 days</li>
</ul>
<p><strong>2. Translation (Accounting) Exposure:</strong></p>
<ul>
<li>Converting foreign subsidiary financial statements to home currency</li>
<li>Even if foreign operations are stable, exchange rate changes affect reported results</li>
</ul>
<p><strong>3. Economic (Operating) Exposure:</strong></p>
<ul>
<li>Long-term competitiveness effects from exchange rate changes</li>
<li>Hardest to measure but potentially most significant</li>
</ul>
</section>
<section id="classroom-example-ganado-corporation" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2"><span class="header-section-number">4.4.2</span> Classroom Example: Ganado Corporation</h3>
<p>Let’s create a simple consolidation example:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb22"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame for Ganado&#39;s subsidiaries</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>subsidiaries <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Subsidiary =</span> <span class="fu">c</span>(<span class="st">&quot;US Parent&quot;</span>, <span class="st">&quot;Europe&quot;</span>, <span class="st">&quot;China&quot;</span>),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Currency =</span> <span class="fu">c</span>(<span class="st">&quot;USD&quot;</span>, <span class="st">&quot;EUR&quot;</span>, <span class="st">&quot;CNY&quot;</span>),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sales_Local =</span> <span class="fu">c</span>(<span class="fl">300.0</span>, <span class="fl">120.0</span>, <span class="fl">600.0</span>),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Earnings_Local =</span> <span class="fu">c</span>(<span class="fl">28.6</span>, <span class="fl">10.5</span>, <span class="fl">71.4</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Exchange_Rate =</span> <span class="fu">c</span>(<span class="fl">1.0000</span>, <span class="fl">1.1200</span>, <span class="fl">0.1515</span>),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rate_Description =</span> <span class="fu">c</span>(<span class="st">&quot;USD 1.00 = USD 1.00&quot;</span>, </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                       <span class="st">&quot;USD 1.12 = EUR 1.00&quot;</span>, </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>                       <span class="st">&quot;CNY 6.60 = USD 1.00&quot;</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate USD equivalents</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>subsidiaries<span class="sc">$</span>Sales_USD <span class="ot">&lt;-</span> subsidiaries<span class="sc">$</span>Sales_Local <span class="sc">*</span> subsidiaries<span class="sc">$</span>Exchange_Rate</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>subsidiaries<span class="sc">$</span>Earnings_USD <span class="ot">&lt;-</span> subsidiaries<span class="sc">$</span>Earnings_Local <span class="sc">*</span> subsidiaries<span class="sc">$</span>Exchange_Rate</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the consolidation</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(subsidiaries, </span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">&quot;Ganado Corporation - Consolidated Results&quot;</span>,</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top">
<caption>Ganado Corporation - Consolidated Results</caption>
<colgroup>
<col style="width: 10%" />
<col style="width: 8%" />
<col style="width: 11%" />
<col style="width: 14%" />
<col style="width: 13%" />
<col style="width: 19%" />
<col style="width: 9%" />
<col style="width: 12%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Subsidiary</th>
<th style="text-align: left;">Currency</th>
<th style="text-align: right;">Sales_Local</th>
<th style="text-align: right;">Earnings_Local</th>
<th style="text-align: right;">Exchange_Rate</th>
<th style="text-align: left;">Rate_Description</th>
<th style="text-align: right;">Sales_USD</th>
<th style="text-align: right;">Earnings_USD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">US Parent</td>
<td style="text-align: left;">USD</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">28.6</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">USD 1.00 = USD 1.00</td>
<td style="text-align: right;">300.0</td>
<td style="text-align: right;">28.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">EUR</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">10.5</td>
<td style="text-align: right;">1.12</td>
<td style="text-align: left;">USD 1.12 = EUR 1.00</td>
<td style="text-align: right;">134.4</td>
<td style="text-align: right;">11.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">CNY</td>
<td style="text-align: right;">600</td>
<td style="text-align: right;">71.4</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: left;">CNY 6.60 = USD 1.00</td>
<td style="text-align: right;">90.9</td>
<td style="text-align: right;">10.82</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb23"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate totals</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Consolidated Totals:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Consolidated Totals:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb25"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total Sales (USD millions):&quot;</span>, <span class="fu">round</span>(<span class="fu">sum</span>(subsidiaries<span class="sc">$</span>Sales_USD), <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Total Sales (USD millions): 525.3 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb27"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total Earnings (USD millions):&quot;</span>, <span class="fu">round</span>(<span class="fu">sum</span>(subsidiaries<span class="sc">$</span>Earnings_USD), <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Total Earnings (USD millions): 51.18 </code></pre>
</div>
</div>
<p><strong>Question:</strong> “If the euro falls from $1.12 to $1.00, what happens to consolidated earnings, even if European operations don’t change?”</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb29"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Original scenario</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>eur_earnings_local <span class="ot">&lt;-</span> <span class="fl">10.5</span>  <span class="co"># million EUR</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>exchange_rate_original <span class="ot">&lt;-</span> <span class="fl">1.12</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>earnings_usd_original <span class="ot">&lt;-</span> eur_earnings_local <span class="sc">*</span> exchange_rate_original</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># New scenario - euro depreciates</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>exchange_rate_new <span class="ot">&lt;-</span> <span class="fl">1.00</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>earnings_usd_new <span class="ot">&lt;-</span> eur_earnings_local <span class="sc">*</span> exchange_rate_new</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate impact</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>impact <span class="ot">&lt;-</span> earnings_usd_new <span class="sc">-</span> earnings_usd_original</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;European Subsidiary Earnings Analysis:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>European Subsidiary Earnings Analysis:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb31"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Local currency earnings (EUR): €&quot;</span>, eur_earnings_local, <span class="st">&quot;million (unchanged)</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Local currency earnings (EUR): € 10.5 million (unchanged)</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb33"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Original scenario:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Original scenario:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb35"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Exchange rate: $&quot;</span>, exchange_rate_original, <span class="st">&quot;/€</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Exchange rate: $ 1.12 /€</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb37"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  USD earnings: $&quot;</span>, <span class="fu">round</span>(earnings_usd_original, <span class="dv">2</span>), <span class="st">&quot;million</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  USD earnings: $ 11.76 million</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb39"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">New scenario (euro depreciation):</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
New scenario (euro depreciation):</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb41"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Exchange rate: $&quot;</span>, exchange_rate_new, <span class="st">&quot;/€</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Exchange rate: $ 1 /€</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb43"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  USD earnings: $&quot;</span>, <span class="fu">round</span>(earnings_usd_new, <span class="dv">2</span>), <span class="st">&quot;million</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  USD earnings: $ 10.5 million</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb45"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Impact on consolidated earnings: $&quot;</span>, <span class="fu">round</span>(impact, <span class="dv">2</span>), <span class="st">&quot;million</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Impact on consolidated earnings: $ -1.26 million</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb47"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Percentage decline: &quot;</span>, <span class="fu">round</span>((impact<span class="sc">/</span>earnings_usd_original)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">1</span>), <span class="st">&quot;%</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage decline:  -10.7 %</code></pre>
</div>
</div>
<p><strong>Answer:</strong> Reported earnings fall by over $1 million purely due to translation!</p>
</section>
</section>
<section id="political-risk" class="level2" data-number="4.5">
<h2 data-number="4.5"><span class="header-section-number">4.5</span> Political Risk</h2>
<p><strong>Definition:</strong> Risk that government actions will adversely affect business operations or asset values.</p>
<section id="types-of-political-risk" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1"><span class="header-section-number">4.5.1</span> Types of Political Risk</h3>
<p><strong>1. Transfer Risk:</strong></p>
<ul>
<li>Blocked funds (cannot repatriate earnings)</li>
<li>Example: Argentina imposing currency controls</li>
</ul>
<p><strong>2. Expropriation:</strong></p>
<ul>
<li>Government seizure of assets</li>
<li>May or may not include compensation</li>
<li>Less common today but still occurs</li>
</ul>
<p><strong>3. Operational Restrictions:</strong></p>
<ul>
<li>Local content requirements</li>
<li>Technology transfer mandates</li>
<li>Forced joint ventures</li>
<li>Price controls</li>
</ul>
<p><strong>4. Regulatory Changes:</strong></p>
<ul>
<li>Tax law changes</li>
<li>Labor law changes</li>
<li>Environmental regulation</li>
</ul>
<p><strong>Recent Examples:</strong></p>
<ul>
<li>Russia’s actions in Ukraine affecting Western companies</li>
<li>China’s regulatory crackdowns on tech companies</li>
<li>India’s changing tax treatment of foreign firms</li>
</ul>
<p><strong>Key Point:</strong> Political risk is hard to quantify, difficult to hedge, but absolutely must be considered in international investment decisions.</p>
</section>
</section>
<section id="modifications-to-financial-theory" class="level2" data-number="4.6">
<h2 data-number="4.6"><span class="header-section-number">4.6</span> Modifications to Financial Theory</h2>
<p>Core financial theories remain valid but require adaptation:</p>
<section id="cost-of-capital" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1"><span class="header-section-number">4.6.1</span> Cost of Capital</h3>
<ul>
<li>Must consider multiple country risk premiums</li>
<li>Currency risk affects required returns</li>
<li>Access to global capital markets can LOWER cost of capital</li>
</ul>
</section>
<section id="capital-budgeting" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2"><span class="header-section-number">4.6.2</span> Capital Budgeting</h3>
<ul>
<li>Project cash flows may be in foreign currency</li>
<li>Repatriation restrictions must be considered</li>
<li>Country risk must be incorporated</li>
<li>Multiple tax jurisdictions complicate analysis</li>
</ul>
</section>
<section id="working-capital-management" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3"><span class="header-section-number">4.6.3</span> Working Capital Management</h3>
<ul>
<li>Multiple currencies to manage</li>
<li>International cash pooling opportunities</li>
<li>More complex credit analysis for foreign customers</li>
</ul>
</section>
<section id="capital-structure" class="level3" data-number="4.6.4">
<h3 data-number="4.6.4"><span class="header-section-number">4.6.4</span> Capital Structure</h3>
<ul>
<li>Access to foreign debt markets</li>
<li>Currency matching strategies (financing in same currency as revenues)</li>
<li>Different optimal leverage ratios in different countries</li>
</ul>
</section>
</section>
<section id="modified-financial-instruments" class="level2" data-number="4.7">
<h2 data-number="4.7"><span class="header-section-number">4.7</span> Modified Financial Instruments</h2>
<p>International finance has adapted standard instruments:</p>
<section id="currency-derivatives" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1"><span class="header-section-number">4.7.1</span> Currency Derivatives</h3>
<ul>
<li>Forward contracts</li>
<li>Futures</li>
<li>Options on currencies</li>
<li>Currency swaps</li>
</ul>
</section>
<section id="interest-rate-instruments" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2"><span class="header-section-number">4.7.2</span> Interest Rate Instruments</h3>
<ul>
<li>Cross-currency interest rate swaps</li>
<li>International bonds (Eurobonds, foreign bonds)</li>
</ul>
</section>
<section id="trade-finance-instruments" class="level3" data-number="4.7.3">
<h3 data-number="4.7.3"><span class="header-section-number">4.7.3</span> Trade Finance Instruments</h3>
<ul>
<li>Letters of credit</li>
<li>Banker’s acceptances</li>
<li>Documentary collections</li>
</ul>
<p><strong>Preview:</strong> We’ll study many of these in detail in later chapters.</p>
<hr />
</section>
</section>
</section>
<section id="the-globalization-process" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> The Globalization Process</h1>
<section id="introducing-ganado-corporation" class="level2" data-number="5.1">
<h2 data-number="5.1"><span class="header-section-number">5.1</span> Introducing Ganado Corporation</h2>
<p><strong>Ganado is our textbook’s case company we’ll follow throughout the semester.</strong></p>
<section id="background" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1"><span class="header-section-number">5.1.1</span> Background</h3>
<ul>
<li>Founded 1948 in Los Angeles</li>
<li>Originally family-owned telecommunications equipment manufacturer</li>
<li>Went public (IPO) in 1988 - became a publicly traded company</li>
<li>Now faces decisions about global expansion</li>
</ul>
<p><strong>Why This Matters:</strong> Ganado’s journey mirrors what thousands of real companies experience as they globalize.</p>
</section>
</section>
<section id="phase-1-domestic-to-international-trade" class="level2" data-number="5.2">
<h2 data-number="5.2"><span class="header-section-number">5.2</span> Phase 1: Domestic to International Trade</h2>
<section id="domestic-phase-characteristics" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1"><span class="header-section-number">5.2.1</span> Domestic Phase Characteristics</h3>
<ul>
<li>All suppliers are domestic (US)</li>
<li>All customers are domestic (US)</li>
<li>All transactions in US dollars</li>
<li>Subject only to US laws and regulations</li>
<li>Credit assessment under familiar US practices</li>
</ul>
<p><strong>Simple and low-risk,</strong> but <strong>limited growth potential.</strong></p>
</section>
<section id="catalyst-for-change" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2"><span class="header-section-number">5.2.2</span> Catalyst for Change</h3>
<p>NAFTA (North American Free Trade Agreement) created opportunities for trade with Mexico and Canada.</p>
</section>
<section id="international-trade-phase" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3"><span class="header-section-number">5.2.3</span> International Trade Phase</h3>
<ul>
<li>BEGIN importing from Mexican suppliers</li>
<li>BEGIN exporting to Canadian customers</li>
<li>NOW dealing with multiple currencies (USD, MXN, CAD)</li>
</ul>
</section>
<section id="two-new-major-challenges" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4"><span class="header-section-number">5.2.4</span> Two New Major Challenges</h3>
<p><strong>1. Foreign Exchange Risk:</strong></p>
<ul>
<li>Which currency to quote prices in?</li>
<li>Which currency to accept payment in?</li>
<li>Which currency to pay suppliers in?</li>
<li>What if exchange rates change between agreement and payment?</li>
</ul>
<p><strong>Example:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb49"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ganado quotes Canadian customer</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>quoted_price_cad <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>exchange_rate_at_quote <span class="ot">&lt;-</span> <span class="fl">1.25</span>  <span class="co"># CAD per USD</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>expected_usd <span class="ot">&lt;-</span> quoted_price_cad <span class="sc">/</span> exchange_rate_at_quote</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># By payment time, CAD depreciates</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>exchange_rate_at_payment <span class="ot">&lt;-</span> <span class="fl">1.30</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>actual_usd <span class="ot">&lt;-</span> quoted_price_cad <span class="sc">/</span> exchange_rate_at_payment</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>loss <span class="ot">&lt;-</span> actual_usd <span class="sc">-</span> expected_usd</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Foreign Exchange Risk Example:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Foreign Exchange Risk Example:</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb51"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Quoted price: CAD&quot;</span>, quoted_price_cad, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Quoted price: CAD 1000 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb53"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Exchange rate at quote: CAD&quot;</span>, exchange_rate_at_quote, <span class="st">&quot;= USD 1.00</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Exchange rate at quote: CAD 1.25 = USD 1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb55"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Expected USD receipt: $&quot;</span>, <span class="fu">round</span>(expected_usd, <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Expected USD receipt: $ 800 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb57"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Exchange rate at payment: CAD&quot;</span>, exchange_rate_at_payment, <span class="st">&quot;= USD 1.00</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Exchange rate at payment: CAD 1.3 = USD 1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb59"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Actual USD receipt: $&quot;</span>, <span class="fu">round</span>(actual_usd, <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Actual USD receipt: $ 769.23 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode" id="cb61"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Loss due to currency movement: $&quot;</span>, <span class="fu">round</span>(loss, <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Loss due to currency movement: $ -30.77 </code></pre>
</div>
</div>
<p><strong>2. Credit Risk Assessment:</strong></p>
<ul>
<li>How creditworthy is Mexican supplier?</li>
<li>Will Canadian customer actually pay?</li>
<li>Different business practices</li>
<li>Different legal systems</li>
<li>Different bankruptcy laws</li>
<li>Less available information</li>
</ul>
<p><strong>Key Point:</strong> Even in this relatively simple international trade phase, financial management complexity increases dramatically compared to purely domestic operations.</p>
</section>
</section>
<section id="phase-2-international-trade-to-multinational-enterprise" class="level2" data-number="5.3">
<h2 data-number="5.3"><span class="header-section-number">5.3</span> Phase 2: International Trade to Multinational Enterprise</h2>
<p><strong>Critical Decision Point:</strong> At some point, successful international trading leads companies to consider foreign direct investment (FDI).</p>
<section id="why-make-this-leap" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1"><span class="header-section-number">5.3.1</span> Why Make This Leap?</h3>
<p><strong>Strategic Motivations (Five Categories):</strong></p>
<p><strong>1. Market Seekers:</strong></p>
<ul>
<li>Produce in foreign markets to serve local demand</li>
<li>Overcome trade barriers</li>
<li>Get closer to customers</li>
<li>Example: US auto manufacturers in Europe</li>
</ul>
<p><strong>2. Raw Material Seekers:</strong></p>
<ul>
<li>Access natural resources where they’re located</li>
<li>Mining, oil, forestry, agricultural products</li>
<li>Example: Oil companies drilling in Middle East</li>
</ul>
<p><strong>3. Production Efficiency Seekers:</strong></p>
<ul>
<li>Take advantage of lower-cost factors of production</li>
<li>Especially labor</li>
<li>Example: Electronics assembly in Malaysia, Vietnam</li>
</ul>
<p><strong>4. Knowledge Seekers:</strong></p>
<ul>
<li>Access technology, expertise, innovation</li>
<li>Example: Japanese and German companies buying US tech firms</li>
</ul>
<p><strong>5. Political Safety Seekers:</strong></p>
<ul>
<li>Diversify political risk</li>
<li>Example: Hong Kong firms investing in Canada, Australia before 1997 Chinese takeover</li>
</ul>
<p><strong>Important Note:</strong> These are not mutually exclusive. One investment may serve multiple purposes.</p>
</section>
</section>
<section id="the-foreign-direct-investment-spectrum" class="level2" data-number="5.4">
<h2 data-number="5.4"><span class="header-section-number">5.4</span> The Foreign Direct Investment Spectrum</h2>
<section id="increasing-foreign-presence-low-to-high" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1"><span class="header-section-number">5.4.1</span> Increasing Foreign Presence (Low to High)</h3>
<p><strong>1. Exporting from Home Production</strong></p>
<ul>
<li>Lowest commitment</li>
<li>Maintain control</li>
<li>Limited foreign presence</li>
</ul>
<p><strong>2. Licensing to Foreign Firms</strong></p>
<ul>
<li>Foreign company produces under your brand/technology</li>
<li>Receive royalties</li>
<li>Low capital investment</li>
<li>Risk: Creating future competitors, loss of quality control</li>
</ul>
<p><strong>3. Joint Venture</strong></p>
<ul>
<li>Partner with local firm (often 50-50 ownership)</li>
<li>Share investment, share risks, share rewards</li>
<li>Common in countries requiring local partners</li>
<li>Challenge: Potential conflicts with partner</li>
</ul>
<p><strong>4. Wholly-Owned Subsidiary - Greenfield</strong></p>
<ul>
<li>Build new facilities from scratch (“greenfield”)</li>
<li>Full control</li>
<li>High investment</li>
<li>Slow to establish</li>
</ul>
<p><strong>5. Wholly-Owned Subsidiary - Acquisition</strong></p>
<ul>
<li>Buy existing foreign company</li>
<li>Fastest market entry</li>
<li>Immediate operations</li>
<li>Integration challenges</li>
<li>Potentially very expensive</li>
</ul>
<p><strong>Key Insight:</strong> As you move down this list:</p>
<ul>
<li><strong>Foreign presence increases</strong> (more physical assets, more employees abroad)</li>
<li><strong>Managerial intensity increases</strong> (more complex to manage)</li>
<li><strong>Capital at risk increases</strong> (more investment)</li>
<li><strong>Potential returns increase</strong> (greater opportunities)</li>
</ul>
</section>
</section>
<section id="consolidation-challenges" class="level2" data-number="5.5">
<h2 data-number="5.5"><span class="header-section-number">5.5</span> Consolidation Challenges</h2>
<p>This is a critical practical issue. Once Ganado has foreign subsidiaries:</p>
<ul>
<li>European subsidiary keeping books in euros</li>
<li>Chinese subsidiary keeping books in yuan</li>
<li>US parent keeping books in dollars</li>
</ul>
<section id="the-problem" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1"><span class="header-section-number">5.5.1</span> The Problem</h3>
<p>Ganado must periodically (quarterly, annually) produce consolidated financial statements in US dollars for:</p>
<ul>
<li>Shareholders</li>
<li>SEC (Securities and Exchange Commission) regulations</li>
<li>Tax purposes</li>
<li>Performance evaluation</li>
</ul>
</section>
<section id="the-process" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2"><span class="header-section-number">5.5.2</span> The Process</h3>
<ol type="1">
<li>Each subsidiary reports in local currency</li>
<li>Convert to common currency (USD) using appropriate exchange rates</li>
<li>Sum to create consolidated totals</li>
</ol>
<p><strong>Critical Issue:</strong> Exchange rates change constantly. From one quarter to the next:</p>
<ul>
<li>Foreign subsidiary performance may be stable</li>
<li>BUT exchange rate changes make it look better or worse</li>
<li>This creates “translation exposure” or “accounting exposure”</li>
</ul>
<hr />
</section>
</section>
</section>
<section id="limits-to-financial-globalization-8-minutes" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Limits to Financial Globalization (8 minutes)</h1>
<section id="not-all-globalization-is-inevitable-or-beneficial" class="level2" data-number="6.1">
<h2 data-number="6.1"><span class="header-section-number">6.1</span> Not All Globalization is Inevitable or Beneficial</h2>
<p>Classical economic theory suggests capital should flow freely to its most productive uses globally. <strong>Reality is more complex.</strong></p>
</section>
<section id="the-twin-agency-problems" class="level2" data-number="6.2">
<h2 data-number="6.2"><span class="header-section-number">6.2</span> The “Twin Agency Problems”</h2>
<p><strong>Agency Problem Definition:</strong> When someone managing assets (agent) has different interests than the asset owners (principals)</p>
<section id="first-agency-problem---corporate-insiders" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1"><span class="header-section-number">6.2.1</span> First Agency Problem - Corporate Insiders</h3>
<ul>
<li>Do managers/executives pursue firm value maximization?</li>
<li>OR do they pursue personal wealth/power?</li>
</ul>
<p><strong>Examples of Value-Destroying Insider Actions:</strong></p>
<ul>
<li>Excessive compensation</li>
<li>Empire building (growth for prestige, not returns)</li>
<li>Resistance to beneficial takeovers</li>
<li>Related-party transactions that benefit insiders</li>
</ul>
</section>
<section id="second-agency-problem---governmentsovereign-insiders" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2"><span class="header-section-number">6.2.2</span> Second Agency Problem - Government/Sovereign Insiders</h3>
<ul>
<li>Do political leaders pursue national economic welfare?</li>
<li>OR do they pursue personal power/wealth?</li>
</ul>
<p><strong>Examples:</strong></p>
<ul>
<li>Corruption</li>
<li>Expropriation</li>
<li>Capital controls that harm economy but protect political power</li>
<li>Regulatory capture</li>
</ul>
</section>
</section>
<section id="consequences-for-global-capital-flows" class="level2" data-number="6.3">
<h2 data-number="6.3"><span class="header-section-number">6.3</span> Consequences for Global Capital Flows</h2>
<p><strong>IF corporate and government insiders pursue value maximization:</strong></p>
<p>→ Capital flows to these opportunities<br />
→ Financial globalization INCREASES<br />
→ Benefits widely shared</p>
<p><strong>IF insiders pursue personal agendas:</strong></p>
<p>→ Capital avoids these situations<br />
→ Financial globalization LIMITED<br />
→ Creates “winners” and “losers”<br />
→ Segmented markets</p>
<section id="real-world-examples" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1"><span class="header-section-number">6.3.1</span> Real-World Examples</h3>
<p><strong>Positive Examples (Attracting Capital):</strong></p>
<ul>
<li>Singapore: Strong rule of law, low corruption, excellent governance</li>
<li>Result: Major financial center despite small size</li>
</ul>
<p><strong>Negative Examples (Capital Flight):</strong></p>
<ul>
<li>Venezuela: Expropriation, corruption, poor governance</li>
<li>Result: Economic collapse, capital flees</li>
</ul>
</section>
</section>
<section id="contemporary-challenges" class="level2" data-number="6.4">
<h2 data-number="6.4"><span class="header-section-number">6.4</span> Contemporary Challenges</h2>
<section id="three-current-issues" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1"><span class="header-section-number">6.4.1</span> Three Current Issues</h3>
<p><strong>1. Inequality:</strong></p>
<ul>
<li>Globalization benefits not evenly distributed</li>
<li>Within-country inequality increasing</li>
<li>“Left behind” populations creating political backlash</li>
</ul>
<p><strong>2. Regulatory Arbitrage:</strong></p>
<ul>
<li>Companies structure operations to minimize taxes</li>
<li>“Tax havens” and profit shifting</li>
<li>Creates political tensions</li>
</ul>
<p><strong>3. National Security vs. Economic Efficiency:</strong></p>
<ul>
<li>Growing restrictions on foreign investment in “strategic” sectors</li>
<li>Technology transfer concerns</li>
<li>Supply chain security concerns</li>
</ul>
<p><strong>Example:</strong> US restrictions on Chinese investment in American technology companies, even when economically beneficial.</p>
</section>
</section>
<section id="the-path-forward" class="level2" data-number="6.5">
<h2 data-number="6.5"><span class="header-section-number">6.5</span> The Path Forward</h2>
<blockquote>
<p>“Welcome to the future. This will be a constant struggle. We need leadership, citizenship, and dialogue.”<br />
- Donald Lessard</p>
</blockquote>
<p><strong>Key Takeaway:</strong> Financial globalization is neither inevitable nor uniformly beneficial. Success requires:</p>
<ul>
<li>Strong institutions</li>
<li>Good governance<br />
</li>
<li>Ethical leadership</li>
<li>Informed citizenry</li>
<li>Ongoing dialogue and adaptation</li>
</ul>
<hr />
</section>
</section>
<section id="conclusion-and-synthesis-5-minutes" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion and Synthesis (5 minutes)</h1>
<section id="connecting-the-dots" class="level2" data-number="7.1">
<h2 data-number="7.1"><span class="header-section-number">7.1</span> Connecting the Dots</h2>
<p>Let me bring together today’s major themes:</p>
<section id="the-global-financial-marketplace-1" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1"><span class="header-section-number">7.1.1</span> The Global Financial Marketplace</h3>
<ul>
<li>Complex ecosystem of securities, institutions, and currency linkages</li>
<li>Larger and more interconnected than ever</li>
<li>Creates both opportunities and risks</li>
</ul>
</section>
<section id="comparative-advantage" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2"><span class="header-section-number">7.1.2</span> Comparative Advantage</h3>
<ul>
<li>Still explains why international trade benefits countries</li>
<li>Modern version focuses on services, skills, technology</li>
<li>Dynamic, not static - shifts over time</li>
</ul>
</section>
<section id="what-makes-international-finance-unique" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3"><span class="header-section-number">7.1.3</span> What Makes International Finance Unique</h3>
<ul>
<li>Foreign exchange risk</li>
<li>Political risk</li>
<li>Cultural and institutional differences</li>
<li>Corporate governance variations</li>
<li>Required modifications to financial theories and instruments</li>
</ul>
</section>
<section id="the-globalization-journey" class="level3" data-number="7.1.4">
<h3 data-number="7.1.4"><span class="header-section-number">7.1.4</span> The Globalization Journey</h3>
<ul>
<li>Progression from domestic → international trade → multinational</li>
<li>Each phase brings new opportunities and new complexities</li>
<li>Not all firms should fully globalize</li>
<li>Not all globalization creates value</li>
</ul>
</section>
<section id="limits-and-challenges" class="level3" data-number="7.1.5">
<h3 data-number="7.1.5"><span class="header-section-number">7.1.5</span> Limits and Challenges</h3>
<ul>
<li>Agency problems at corporate and sovereign levels</li>
<li>Potential for value destruction</li>
<li>Ongoing tension between efficiency and other goals (security, equity, stability)</li>
</ul>
</section>
</section>
<section id="looking-ahead" class="level2" data-number="7.2">
<h2 data-number="7.2"><span class="header-section-number">7.2</span> Looking Ahead</h2>
<p><strong>Next chapters will build on this foundation:</strong></p>
<ul>
<li>Chapter 2: International Monetary System - How currencies interact, exchange rate regimes</li>
<li>Chapter 3: Balance of Payments - How we track international flows</li>
<li>Chapter 4: Corporate Governance in depth - Different models worldwide</li>
<li>Later: Foreign exchange markets, currency derivatives, international investment, multinational capital budgeting</li>
</ul>
</section>
<section id="why-this-matters-to-you" class="level2" data-number="7.3">
<h2 data-number="7.3"><span class="header-section-number">7.3</span> Why This Matters to You</h2>
<section id="career-relevance" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1"><span class="header-section-number">7.3.1</span> Career Relevance</h3>
<ul>
<li>Almost every major company operates internationally</li>
<li>Understanding these concepts makes you more valuable</li>
<li>Finance, marketing, operations, strategy all require international awareness</li>
</ul>
</section>
<section id="citizenship" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2"><span class="header-section-number">7.3.2</span> Citizenship</h3>
<ul>
<li>Trade policy</li>
<li>Tax policy</li>
<li>Immigration</li>
<li>National security</li>
</ul>
<p>All involve international finance concepts.</p>
</section>
<section id="personal-finance" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3"><span class="header-section-number">7.3.3</span> Personal Finance</h3>
<ul>
<li>International diversification</li>
<li>Currency considerations</li>
<li>Understanding global markets</li>
</ul>
</section>
</section>
<section id="practical-advice-for-success-in-this-course" class="level2" data-number="7.4">
<h2 data-number="7.4"><span class="header-section-number">7.4</span> Practical Advice for Success in This Course</h2>
<section id="stay-current" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1"><span class="header-section-number">7.4.1</span> Stay Current</h3>
<ul>
<li>Read <em>Financial Times</em>, <em>Wall Street Journal</em>, <em>The Economist</em></li>
<li>Follow exchange rates</li>
<li>Track international business news</li>
</ul>
</section>
<section id="think-critically" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2"><span class="header-section-number">7.4.2</span> Think Critically</h3>
<ul>
<li>Don’t just memorize formulas</li>
<li>Understand the “why” behind concepts</li>
<li>Question assumptions</li>
</ul>
</section>
<section id="connect-concepts" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3"><span class="header-section-number">7.4.3</span> Connect Concepts</h3>
<ul>
<li>International finance is integrative</li>
<li>Links to economics, politics, strategy, culture</li>
<li>Make connections across chapters</li>
</ul>
</section>
<section id="use-real-examples" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4"><span class="header-section-number">7.4.4</span> Use Real Examples</h3>
<ul>
<li>Apply concepts to companies you know</li>
<li>Follow a multinational company throughout semester</li>
<li>Analyze current events through international finance lens</li>
</ul>
<hr />
</section>
</section>
</section>
<section id="questions-and-discussion-5-10-minutes" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Questions and Discussion (5-10 minutes)</h1>
<section id="check-for-understanding" class="level2" data-number="8.1">
<h2 data-number="8.1"><span class="header-section-number">8.1</span> Check for Understanding</h2>
<p><strong>Key Questions to Pose:</strong></p>
<ol type="1">
<li><p>“Can someone explain in their own words what makes the eurocurrency market different from domestic banking?”</p></li>
<li><p>“Why might a country with absolute advantage in producing everything still benefit from trade?”</p></li>
<li><p>“What’s the single biggest risk factor that distinguishes international from domestic finance?”</p></li>
<li><p>“If the dollar strengthens against all foreign currencies, what generally happens to US multinationals’ consolidated earnings, all else equal?”</p></li>
</ol>
</section>
<section id="preview-next-class" class="level2" data-number="8.2">
<h2 data-number="8.2"><span class="header-section-number">8.2</span> Preview Next Class</h2>
<p><strong>Next session we’ll dive into:</strong></p>
<ul>
<li>The International Monetary System (Chapter 2)</li>
<li>Fixed vs. floating exchange rates</li>
<li>The role of the IMF and World Bank</li>
<li>Major currency crises in history</li>
<li>The future of the dollar as reserve currency</li>
</ul>
<p><strong>Assignment for Next Class:</strong></p>
<ul>
<li>Read Chapter 2</li>
<li>Find a current article about exchange rate movements</li>
<li>Be prepared to discuss why that currency moved</li>
</ul>
<hr />
</section>
</section>
<section id="final-thoughts-2-minutes" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Final Thoughts (2 minutes)</h1>
<p>International finance is one of the most dynamic, challenging, and relevant fields in business today. Every concept we study has real-world application. Every formula we learn represents actual business decisions.</p>
<p>The world is more connected than ever, which creates unprecedented opportunities for those who understand how to navigate the global financial marketplace. It also creates risks for those who don’t.</p>
<p>My goal is to help you develop not just technical competence, but also strategic insight and critical thinking about international finance. This first chapter laid the foundation - now we build.</p>
<p>See you next class. Please review Chapter 1, attempt the practice problems, and don’t hesitate to email me with questions.</p>
<div id="quarto-navigation-envelope" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyLXRpdGxl">International Finance</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXItdGl0bGU=">International Finance</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyOnF1YXJ0by1zaWRlYmFyLXNlY3Rpb24tMQ==">Lecture Notes</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6SG9tZQ==">Home</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L2luZGV4Lmh0bWw=">/index.html</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6U3lsbGFidXM=">Syllabus</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L3N5bGxhYnVzLnFtZA==">/syllabus.qmd</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6U2NoZWR1bGU=">Schedule</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L3NjaGVkdWxlLnFtZA==">/schedule.qmd</span></p>
</div>
<div id="quarto-meta-markdown" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGF0aXRsZQ==">International Finance - Chapter 1 – International Finance</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkdGl0bGU=">International Finance - Chapter 1 – International Finance</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZHRpdGxl">International Finance - Chapter 1 – International Finance</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGFzaXRlbmFtZQ==">International Finance</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkZGVzYw==">Multinational Financial Management: Opportunities and Challenges</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZGRkZXNj">Multinational Financial Management: Opportunities and Challenges</span></p>
</div>
</section>

</main> <!-- /main -->
<script id = "quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->

</body>

</html>
